# -*- coding: utf-8 -*-
"""Leadership and commercial-roster research for the 61-company list (2026-08-21).

Only CEO Research and Commercial People are touched.  Where no leader is named
in any public source the row says so rather than guessing; where the listed name
is the legal entity behind a brand already in the workbook, the row cross-refers
instead of duplicating the research.
"""

NF = "Bachelor: not found. Master: not found. PhD: not found."

CEO_ROWS = [
["Sogrape","Fernando da Cunha Guedes","President and CEO",
 "Third-generation head of the Portuguese family group founded in 1942, the owner of Sandeman, Mateus and a portfolio spanning Portugal, Spain, Chile, Argentina, New Zealand and Australia; the group is present in Romania through import and distribution rather than production.",
 "Bachelor/equivalent: business studies (institution not stated in reviewed sources). Master: not found. PhD: not found.",
 "Family ownership; international wine group management; export and distribution; brand portfolio.",
 "https://www.linkedin.com/in/fernando-da-cunha-guedes-32152246/",
 "High confidence on role. Portuguese group, not a Romanian producer — listed here because it appears on the Romanian market list."],
["Bodega Pietroasa","Not publicly identified","—",
 "A Dealu Mare producer working the hills at Zorești, Buzău, whose cellar was modernised in 2006 and which bottles the Basilevs range. Distinct from the Pietroasa research station (SCDVV, founded 1893) and from Crama Pietroasele.",
 NF,
 "Viticulture; wine production; regional branded ranges.",
 "https://bodegapietroasa.ro/",
 "No owner, CEO or general manager is named on the winery's own site or in any reviewed public source. Identity confirmed only at company level."],
["Cricova","Leadership in transition — see notes","Director General, S.A. Combinatul de Vinuri „Cricova”",
 "Moldova's state-owned flagship cellar. Valentin Bodiul ran it as director general from 1987 to 2016 and died of COVID-19 in October 2020; Denis Șova won the competition for the post and was then dismissed by the board in 2022, and a fresh competition was advertised by the Public Property Agency in September 2024.",
 NF,
 "State-owned enterprise management; wine production; wine tourism.",
 "https://app.gov.md/cariere-in-entitati/director-al-s-a-combinatul-de-vinuri-cricova-2/",
 "Low-to-medium confidence: the post has changed hands repeatedly and no confirmed incumbent was found as of 2026-08-21. Moldovan state-owned company, not a Romanian producer."],
["Ostrovit","Oana Belu","CEO",
 "Ostrovit S.A. is the operating company behind the Domeniile Ostrov brand already researched in this workbook; leadership, background and education are recorded on the Domeniile Ostrov row.",
 "See the Domeniile Ostrov row.",
 "See the Domeniile Ostrov row.",
 "https://www.domeniileostrov.ro/pages/despre-domeniile-ostrov",
 "Cross-reference, not a separate company: listed name is the legal entity behind Domeniile Ostrov. Not double-counted anywhere in this workbook."],
["Rovinex","Not publicly identified","—",
 "A Romanian wine brand with close to thirty years on the market, sold through national retail and online, including a Romanian Classic range.",
 NF,
 "Branded wine production and distribution.",
 "https://nitelashop.ro/rovinex-vin-rose-romanian-classic-cabernet-sauvignon-2-bucati-x-0-75l",
 "No leadership is named in any reviewed public source; the brand has no reachable corporate site. Low confidence on company identity."],
["Vinarte","Not publicly identified","—",
 "Founded in 1998 by Romanian, French and Italian investors, working about 120 hectares at Stârmina in Mehedinți and 50 at Sâmburești in Olt under the Castel Stârmina and Bolovanu names. Sold its Villa Zorilor estate and the Prince Matei brand to Vintruvian Estates in 2019.",
 NF,
 "Viticulture; winemaking; foreign investment in Romanian wine.",
 "https://winesofromania.com/en/wineries/vinarte/",
 "Founding investors are documented but no current CEO or general manager is named publicly. Medium confidence on company facts, none on leadership."],
["Vinexport","Not publicly identified","—",
 "Listed on the Romanian market as a wine company; no corporate site or company profile could be reached from the name alone.",
 NF,
 "Not established from public sources.",
 "—",
 "Nothing verifiable was located for this name. It may be a trade name or a company whose registered name differs — worth confirming the legal entity before further research."],
["Carpatvin","Not publicly identified","—",
 "Carpatvin Grup SRL of Odobești, Vrancea, which took over and continues the Odobești wine-processing facility founded in 1976, and distributes bottled wine through Kaufland, Carrefour, Auchan, Mega Image and Penny Market plus regional distributors.",
 NF,
 "Wine processing; bottling; national retail distribution.",
 "https://www.carpatvin.ro/despre/",
 "Company identity and distribution footprint are documented on its own site; no named leadership appears there or in reviewed public sources."],
["Chateau Vartely","Arcadie Foșnea","Director of Technical Operations",
 "Winemaker at the Orhei estate, named Moldovan Winemaker of the Year in 2014, who studied winemaking at Weinsberg in Germany. The winery employs about 350 people, exports to more than twenty countries and produces over a million bottles a year.",
 "Bachelor/equivalent: winemaking, Weinsberg (Germany). Master: not found. PhD: not found.",
 "Oenology; technical operations; export production.",
 "https://wineofmoldova.com/en/chateau-vartely-winery/",
 "Medium confidence as a leadership entry: Foșnea is the senior figure named publicly but holds a technical, not a general-management title, and no CEO or general manager is published. Moldovan producer."],
["Bucium","Not publicly identified","—",
 "Listed on the Romanian market as a wine company associated with the Bucium vineyard near Iași; no corporate site or leadership could be reached from the name alone.",
 NF,
 "Not established from public sources.",
 "—",
 "Nothing verifiable was located. The Bucium name attaches to a vineyard area and to more than one entity, so the legal entity should be confirmed before further research."],
["Domeniile Panciu","Daniel Guzu","Owner",
 "Set out in 2006 to revive the winemaking tradition of the Panciu region and built an estate of more than 120 hectares at Țifești, working both French and Romanian varieties, with a winery-and-resort operation attached.",
 NF,
 "Entrepreneurship; viticulture; wine tourism and hospitality.",
 "https://www.blog.desprevin.ro/interviu-daniel-guzu-proprietar-domeniile-panciu/",
 "High confidence on ownership from a published interview. Oenologist is Sorin Macoviciuc; resort manager Cristina Cărutașu."],
["Doina Vin","Not publicly identified","—",
 "Listed on the Romanian market as a wine company; no corporate site or company profile could be reached from the name alone.",
 NF,
 "Not established from public sources.",
 "—",
 "Nothing verifiable was located for this name. Confirm the legal entity before further research."],
["Rifco Import","Not publicly identified","—",
 "Listed on the Romanian market as a wine importer; no corporate site or company profile could be reached from the name alone.",
 NF,
 "Import and distribution (inferred from the trade name).",
 "—",
 "Nothing verifiable was located. Named as an importer rather than a producer, so the research shape differs — a commercial roster would matter more than a winemaker."],
["Corcova","Michel Roy and Șerban Dâmboviceanu","Founders and owners",
 "Founded the Mehedinți estate in 2005 on land with a winegrowing history reaching back to the Bibescu family, restoring and re-equipping the cellars in 2008–2009; the estate works about 70 hectares and bottles roughly 375,000 litres a year.",
 NF,
 "Entrepreneurship; viticulture; estate restoration; premium wine.",
 "https://winesofromania.com/en/wineries/corcova-roy-damboviceanu/",
 "High confidence on the founding partnership; no single CEO title is published. Emil Mogoșanu is the published contact and Liviu Grigorică the oenologist."],
["DC Segarcea","Mihai Anghel","Owner (with Cornelia Anghel)",
 "The Anghel family took the Segarcea royal estate over from the Romanian state in 2002 and rebuilt it as Domeniul Coroanei Segarcea; Mihai Anghel also owns the Cerealcom Dolj agricultural group and has pushed the wines into export.",
 NF,
 "Agriculture; grain trading; wine estate ownership; export.",
 "https://domeniulcoroanei.com/povestea-domeniului-coroanei-segarcea/",
 "High confidence on ownership since 2002; no separate CEO or general-manager title is published for the winery."],
["Casa Isarescu","Mugur Isărescu","Owner (with Ileana, Costin and Lăcrămioara Isărescu)",
 "Governor of the National Bank of Romania and owner of the Drăgășani estate founded in 2003, working about 45 hectares and bottling some 200,000 litres a year through the operating company Măr SRL, which reported 6.2 million lei of revenue and an 18% profit margin in 2023; the estate also runs a guesthouse and restaurant.",
 "Bachelor/equivalent and doctorate in economics, Academy of Economic Studies, Bucharest (from his public central-banking biography).",
 "Central banking; economics; agriculture and wine estate ownership; wine tourism.",
 "https://casaisarescu.ro/istorie",
 "High confidence on ownership and business figures. The owner's public life is banking, not wine — the winery is a family business rather than his executive role."],
["Castel Mimi","Adrian Trofim","CEO / General Manager",
 "Runs the Bulboaca estate built in 1893 by Constantin Mimi, the last governor of Tsarist Bessarabia, which the Trofim family restored between 2011 and 2016 into Moldova's most comprehensive winery restoration and reopened as a wine-and-resort complex; the winery drew a €1.24 million investment in 2025 for a wellness centre and sustainable growth.",
 NF,
 "General management; wine production; hospitality and wine tourism; heritage restoration.",
 "https://castelmimi.md/despre-noi/",
 "High confidence on role. Owner is Iurie Trofim. Moldovan producer. Adrian Trofim is also the co-author of the Tandem collaboration with Liliac's Miron Radić recorded on the Liliac row."],
["Alexandrion","Antonio Salameh","Chairman, Nawaf Salameh Family Office; leads the group in Romania",
 "Eldest son of founder Nawaf Salameh, who built Alexandrion from 2001 into the Romanian leader in spirits and wine production and distribution with turnover above 800 million lei, added the Romanian wine portfolio bought from Halewood, and died on 20 April 2025 aged 59; Antonio and his brother Roberto had been brought in as vice-presidents before that.",
 NF,
 "Spirits and wine production and distribution; family holding management; real estate, agriculture and tourism.",
 "https://www.profit.ro/insider/companii/nawaf-salameh-se-retrage-din-postul-de-ceo-al-alexandrion-18199575",
 "High confidence on the founder and on the succession following his death in April 2025; the exact current CEO title inside the Romanian operating company is not published."],
["Suvorov Vin","Not publicly identified","—",
 "A Moldovan wine company listed on the Romanian market; no corporate site or leadership could be reached from the name alone.",
 NF,
 "Not established from public sources.",
 "—",
 "Nothing verifiable was located. Moldovan producer; confirm the legal entity before further research."],
["Barefoot Cellars","Michael Houlihan and Bonnie Harvey","Founders (brand now owned by E. & J. Gallo)",
 "Founded the brand in 1986 in California with its footprint label and built it into the world's largest wine brand before selling the producing company, Grape Links Inc., to the Gallo family; the brand is present in Romania through import and retail distribution.",
 NF,
 "Entrepreneurship; brand building; mass-market wine; publishing and speaking.",
 "https://www.transitionsib.com/the-backstory-behind-e-j-gallos-acquisition-of-barefoot-cellars/",
 "High confidence on the founders and the sale. American brand inside E. & J. Gallo, not a Romanian producer — day-to-day leadership sits within Gallo and is not published per brand."],
["Domeniul Bogdan","Bogdan Mihalcea","Owner",
 "Planted 154 hectares near Peștera in Dobrogea in 2011 and built Romania's first biodynamic wine farm, working the estate under organic and biodynamic certification.",
 NF,
 "Entrepreneurship; biodynamic and organic viticulture; premium wine.",
 "https://www.winesday.ro/povestea-cramei-domeniul-bogdan-interviu/",
 "High confidence on ownership and on the biodynamic positioning, from a published interview."],
["Crama Basilescu","Ilie Buican","Owner",
 "Recovered the historic Basilescu estate at Urlați through a restitution process begun in 1993 and concluded in 2007, then laid the foundations of the present winery in 2008.",
 NF,
 "Ownership; estate restitution and rebuilding; wine production; wine tourism.",
 "https://jurnalul.ro/bani-afaceri/economia/p-crama-basilescu-recuperata-dupa-cinci-decenii-777011.html",
 "High confidence on ownership. Winemaker is Cătălin Costache and the winery manager is Dana Sofia."],
["Avincis Vinuri","Gheorghe Lixandru","Executive Director",
 "Agronomic engineer running the Drăgășani estate founded in 2007, when Cristiana Irinel Stoica returned with her husband Valeriu Stoica and daughter Andreea to the family's Vila Dobrușa property; the oenological council is coordinated by Valeriu Stoica with Italian consultants Federico Giotto and Stefano Saderi.",
 "Bachelor/equivalent: agronomic engineering (institution not stated in reviewed sources). Master: not found. PhD: not found.",
 "Agronomy; estate management; viticulture; wine tourism.",
 "https://www.avincis.ro/echipa-noastra.htm",
 "High confidence: the winery publishes its own team page with titles. Shareholders are Valeriu Stoica, Cristiana Irinel Stoica, Andreea Micu and Emilia Chirițescu."],
["Crama La Salina","Not publicly identified","—",
 "A Turda winery operating as Crama La Salina S.A. beside the salt mine, bottling the ISSA and SATYR labels and running a wine-tourism operation; Ovidiu Maxim is the named wine expert.",
 NF,
 "Winemaking; wine tourism and hospitality.",
 "https://www.crameromania.ro/crame/crama-la-salina-turda.html",
 "No CEO or general manager is named publicly; the only named figure is the wine expert. Medium confidence on company facts."],
["Mastegariu Florin","Not publicly identified","—",
 "The name appears on the Romanian wine market list but resolves to no company site, producer profile or trade record in any reviewed source.",
 NF,
 "Not established from public sources.",
 "—",
 "Nothing verifiable was located. The name reads as a personal name rather than a company — it may be a sole trader (PFA) or an authorised person on a licence; confirm before further research."],
["Unicom","Not publicly identified","—",
 "No wine company could be resolved from this name. The reachable Romanian company trading as Unicom Holding operates in fuel cards and logistics, which does not match a wine list.",
 NF,
 "Not established from public sources.",
 "—",
 "Ambiguous name with at least one large unrelated Romanian company attached to it. Confirm the legal entity before further research."],
["Antinori","Albiera Antinori","President (CEO: Renzo Cotarella)",
 "Heads the Florentine family firm founded in 1385, now in its twenty-sixth generation; Renzo Cotarella is chief executive and chief oenologist and was named the Institute of Masters of Wine Winemakers' Winemaker for 2026. The group is present in Romania through import and distribution.",
 NF,
 "Family ownership; international fine wine; estate management; oenology (Cotarella).",
 "https://www.mastersofwine.org/news/renzo-cotarella-awarded-the-2026-institute-of-masters-of-wine-winemakers-winemaker-award/",
 "High confidence on both roles. Italian group, not a Romanian producer — listed here because it appears on the Romanian market list."],
["Fautor","Tatiana Croitoru","Oenologist and senior technical lead",
 "Leads winemaking at the Tigheci estate in the Valul lui Traian region of southern Moldova, a family company re-equipped between 2003 and 2006 and now working more than 350 hectares; Fautor was named Moldova's most awarded producer for six consecutive years from 2017 to 2022.",
 "Bachelor/equivalent: oenology (institution not stated in reviewed sources). Master: not found. PhD: not found.",
 "Oenology; technical leadership; premium white wine production.",
 "https://wineofmoldova.com/en/fautor-winery/",
 "Medium confidence as a leadership entry: no CEO or general manager is published, and the family owners are not named in reviewed sources. Moldovan producer. Ruxanda Lipcan is the Sales and Marketing Director."],
["Caraprodvin","Acquired by Purcari Wineries — see notes","—",
 "A Vrancea wine producer whose acquisition was signed by Crama Ceptura, the Purcari group's Romanian entity, and communicated in 2026 as the group's expansion into Vrancea.",
 NF,
 "Wine production; regional supply.",
 "https://purcariwineries.com/purcari-wineries-se-extinde-in-vrancea/",
 "Now inside the Purcari group; no independent leadership is published post-transaction. The transaction itself is recorded on the Crama Ceptura campaign rows."],
["Grand Tokaj","Götz István","Chief Executive (vezérigazgató)",
 "Took over the largest wine company of Hungary's Tokaj region in September 2025 after two decades inside the firm, most recently as production and operations director, and was presented publicly at the Tokaj-Hegyalja harvest days in October 2025; he succeeded Juhász Szabolcs, appointed only in February of the same year.",
 NF,
 "Wine production and operations; state-owned enterprise leadership.",
 "https://index.hu/belfold/2025/10/07/grand-tokaj-vezerigazgato-gotz-istvan-tokaj-hegyalja-szureti-napok/",
 "High confidence on the September–October 2025 appointment. Hungarian state-owned company, not a Romanian producer."],
["Vinia","Vasile Băbușanu","Director General",
 "Heads the Iași wine company founded in 1950, which operates as a producer and notably as an exporter.",
 NF,
 "Wine production; export; state-successor enterprise management.",
 "https://old.vinul.ro/vinia.html",
 "Medium confidence: the title is documented but the source is an archived producer directory, so the appointment should be re-confirmed before use."],
["Domeniul Burcilor","Not publicly identified","—",
 "Listed on the Romanian market as a wine company; no corporate site or company profile could be reached from the name alone.",
 NF,
 "Not established from public sources.",
 "—",
 "Nothing verifiable was located. Confirm the legal entity before further research."],
["Prodimas","Not publicly identified","—",
 "Listed on the Romanian market as a wine company; no corporate site or company profile could be reached from the name alone.",
 NF,
 "Not established from public sources.",
 "—",
 "Nothing verifiable was located. The name pattern suggests a distributor rather than a producer."],
["WineRo","Not publicly identified","—",
 "Listed on the Romanian market as a wine company; no corporate site or company profile could be reached from the name alone.",
 NF,
 "Not established from public sources.",
 "—",
 "Nothing verifiable was located. The name pattern suggests an importer or distributor rather than a producer."],
["Casa De Vinuri Ciumbrud","Florin Dănoaie","Founder",
 "Founded the company that became the authorised distributor of Domeniile Boieru SRL, producer of Ciumbrud wine in Alba; Raul Ciurtin entered the shareholding in 2017 through a capital increase via Crisware Holdings, taking 50%. The producing company, Domeniile Boieru, has pushed into canned wine and ready-to-drink wine cocktails.",
 NF,
 "Wine retail and distribution; shareholding and investment (Ciurtin).",
 "https://alba24.ro/domeniul-ciumbrud-noi-directii-primele-succese-840872.html",
 "Medium-high confidence on the founder and the 2017 shareholding change. Note the split: Casa de Vinuri Ciumbrud is the distributor, Domeniile Boieru the producer."],
["Domeniile Blaga","Not publicly identified","—",
 "Domeniile Blaga SRL of Fințești, Comuna Năeni, Buzău, founded in 2010 in the Dealu Mare DOC, working about 40 hectares and producing 150,000 to 200,000 litres a year; Cristian Duță is the named wine expert.",
 NF,
 "Viticulture; wine production.",
 "https://domeniileblaga.ro/domeniile-blaga-despre-noi/",
 "Company facts are documented on its own site; no owner, CEO or general manager is named there or in reviewed public sources."],
["Carl Reh Winery","Gabriel Roceanu","General Manager",
 "Carl Reh Winery SRL is the legal entity behind the Crama Oprișor brand already researched in this workbook; leadership, ownership by Reh Kendermann GmbH and the full commercial team are recorded on the Crama Oprișor rows.",
 "See the Crama Oprișor row.",
 "See the Crama Oprișor row.",
 "https://www.crama-oprisor.com/about_us_team.html",
 "Cross-reference, not a separate company: listed name is the legal entity behind Crama Oprișor. Its eight commercial staff are filed under Crama Oprișor and are not double-counted here."],
["Amb Wine Company","Miron Radić","CEO / General Manager",
 "amb Wine Company SRL is the operating company behind the Liliac Winery brand already researched in this workbook; leadership, education and background are recorded on the Liliac Winery row.",
 "See the Liliac Winery row.",
 "See the Liliac Winery row.",
 "https://www.bestjobs.eu/company-profile/amb-wine-company",
 "Cross-reference, not a separate company: listed name is the operating company behind Liliac Winery. Not double-counted anywhere in this workbook."],
["Vintruvian","Marius Iliev","General Manager / founder-level leader",
 "Vintruvian Estates is the group behind Via Viticola, already researched in this workbook, and the buyer of Villa Zorilor and the Prince Matei brand from Vinarte in 2019; leadership and background are recorded on the Via Viticola row.",
 "See the Via Viticola row.",
 "See the Via Viticola row.",
 "https://www.vintruvianestates.com/",
 "Cross-reference, not a separate company: listed name is the group behind Via Viticola. Its four commercial staff are filed under Via Viticola and are not double-counted here."],
]

# Commercial (marketing / sales) staff found for the newly researched companies.
PEOPLE_ROWS = [
["Avincis Vinuri","Ana Pricop","Marketing","Communication Manager","PR / Communications","Manager",
 "https://www.avincis.ro/echipa-noastra.htm"],
["Domeniile Panciu","Marian Apostol","Sales","Commercial Director — wines","Commercial Leadership","Leadership",
 "https://www.domeniilepanciu.ro/contact"],
["Fautor","Ruxanda Lipcan","Sales","Sales & Marketing Director","Commercial Leadership","Leadership",
 "https://wineofmoldova.com/en/fautor-winery/"],
]
