# -*- coding: utf-8 -*-
"""Public-source research for the wineries added to the marketing workbook.

Every row here traces to the URL stored alongside it. Where the workbook's
original source (a LinkedIn session captured 2026-08-18) could not be
reproduced, the field is left empty and the note says so rather than guessing.
"""

CHECK = "2026-08-21"

# name -> dict of sheet payloads.  Column meanings follow the workbook headers.
WINERIES = [
{
 "name": "Crama Gîrboiu",
 "members": None,
 "bestjobs": ("https://www.bestjobs.eu/company-profile/crama-girboiu", 6),
 "site": "https://cramagirboiu.ro/",
 "dept_note": "No LinkedIn capture available; BestJobs employer profile lists 6 alumni (checked 2026-08-21)",
 "ceo": ["Constantin Gîrboiu", "Founder and owner",
   "Founded the family winery at Cotești, Vrancea in 2005 and built it to about 200 hectares and 1.3–1.5 million litres a year, with a branded ladder running from Ambra and Cuartz up to the Tectonic and Epicentrum premium lines.",
   "Bachelor: not found. Master: not found. PhD: not found.",
   "Viticulture; winemaking; family entrepreneurship; branded portfolio building; export.",
   "https://cramagirboiu.ro/despre-crama/",
   "High confidence on founder and ownership. No separate CEO title is published; Livia Gîrboiu appears publicly as Executive Manager of the winery."],
 "positions": [
   ["No dedicated vacancy page located", "Website review", "—", "No website listing found",
    f"Official website checked {CHECK}",
    "The served pages carry winery, portfolio, news and shop sections but no careers or vacancy route.",
    "https://cramagirboiu.ro/"],
   ["BestJobs employer profile (6 alumni)", "Job-board review", "Cotești, Vrancea",
    "Employer profile active; no open role visible at check", f"BestJobs company profile checked {CHECK}",
    "The winery's only public recruitment presence found. No live listing was visible in the page served at check.",
    "https://www.bestjobs.eu/company-profile/crama-girboiu"]],
 "campaigns": [
   ["2025", "„Roata Vinului” consumer promotion", "Seasonal promotion",
    "Prize-wheel mechanic running 1 Feb – 31 May 2025 under a published campaign regulation",
    "A long, four-month promotional window rather than a burst — the mechanic is built to run alongside the trade year rather than to spike it.",
    "https://cramagirboiu.ro/roata-vinului-2/regulament/"],
   ["2025", "Decanter World Wine Awards gold and Best Value", "Awards / reputation",
    "Tectonic Fetească Neagră Barrique took gold plus the Best Value title in London, following 95 Decanter points for the 2022 vintage",
    "Best Value is the rarer prize: it argues price-to-quality, which is the claim a mid-priced native red actually needs.",
    "https://cramagirboiu.ro/blog/crama-girboiu-aur-decanter-2025/"],
   ["2026", "MUNDUS VINI Spring Tasting 2026", "Awards / reputation",
    "21 medals including three Grand Golds, and a fourth consecutive Best Romanian Producer title",
    "Repeat-winning one competition builds a defensible claim no single medal can — the producer title, not the wine, becomes the asset.",
    "https://www.vrancea24.ro/crama-girboiu-scrie-istorie-la-mundus-vini-spring-tasting-2026-21-de-medalii-dintre-care-3-mari-medalii-de-aur/"],
   ["Mar. 2026", "WineCon Fine Wine Exhibition, Chengdu", "Trade / export",
    "Represented Romania at the Shangri-La Chengdu fair as a stated internationalisation step",
    "Picks a single distant market to work properly rather than spreading trade spend across many European fairs.",
    "https://www.monitoruldevrancea.ro/2026/03/24/foto-crama-girboiu-reprezinta-romania-la-winecon-fine-wine-exhibition-chengdu-2026/"],
   ["2026", "Decanter World Wine Awards 2026", "Awards / reputation",
    "Six medals, level with Crama Ceptura and behind only Casa de Vinuri Cotnari and Murfatlar among Romanian producers",
    "Keeps the annual comparison point live in the same competition that produced the 2025 Best Value headline.",
    "https://winesofromania.com/en/romania-decanter-world-wine-awards-2026/"],
   ["Recurring", "Named-tier portfolio ladder", "Portfolio marketing",
    "Ambra, Cuartz, Livia, Bacanta, Tectonic, Epicentrum and Varancha cover entry to premium under one winery name",
    "Distinct range names let the awards story attach to the top tiers without repricing the volume wines.",
    "https://cramagirboiu.ro/vinurile-crama-girboiu/"]],
 "people": [],
 "takeaway": ["No open role found. Recruitment presence is limited to a BestJobs employer profile with 6 alumni; the official site carries no careers route.",
   "Competition-led reputation building, anchored on repeat MUNDUS VINI producer titles, plus a long consumer prize promotion and selective export fairs",
   "Roata Vinului 2025; Decanter 2025 gold and Best Value; MUNDUS VINI Spring 2026 (21 medals); WineCon Chengdu 2026; Decanter 2026",
   "https://cramagirboiu.ro/",
   "Awards and campaign evidence are strong and current. No commercial staff are named in public sources, so the roster and type split are empty rather than estimated."],
},
{
 "name": "Domeniile Vânju Mare",
 "members": None,
 "bestjobs": ("https://www.bestjobs.eu/company-profile/vie-vin-vinju-mare", None),
 "site": "https://domeniilevinjumare.ro/",
 "dept_note": "No LinkedIn capture available; BestJobs employer profile exists, alumni count not published (checked 2026-08-21)",
 "ceo": ["Ion Gîrniță", "Co-owner, SC Vie Vin Vânju Mare SRL",
   "Co-owner with Augustin Popescu of the company formed in 2001 to buy 240 hectares in the Plaiurile Drâncei area; the estate today works about 130 hectares and bottles roughly 350,000 litres a year.",
   "Bachelor: not found. Master: not found. PhD: not found.",
   "Viticulture; wine production; ownership; regional red-wine development.",
   "https://www.crameromania.ro/crame/crama-vinju-mare-73.html",
   "Medium confidence: ownership is documented, but no CEO or general-manager title is published for either owner. Oenologist Florian Stana is the named technical lead."],
 "positions": [
   ["No dedicated vacancy page located", "Website review", "—", "No website listing found",
    f"Official websites checked {CHECK}",
    "Neither the Domeniile Vînju Mare site nor the Vie Vin Vînju Mare producer site serves a careers or vacancy section.",
    "https://domeniilevinjumare.ro/"],
   ["BestJobs employer profile", "Job-board review", "Vânju Mare, Mehedinți",
    "Employer profile active; no open role visible at check", f"BestJobs company profile checked {CHECK}",
    "Profile is listed under the producing company, Vie Vin Vînju Mare. No live listing was visible in the page served at check.",
    "https://www.bestjobs.eu/company-profile/vie-vin-vinju-mare"]],
 "campaigns": [
   ["Sept. 2026", "Festivalul Viei și Vinului, Vânju Mare (35th edition)", "Culture / heritage",
    "Town wine-and-vine festival on 17–18 September 2026 at the „Nichita Stănescu” cultural centre, built around a folk-music interpretation contest",
    "The brand borrows a civic festival older than itself, which buys local legitimacy no owned event could.",
    "https://www.roevent.org/2026/festivalul-viei-si-vinului-2026-concurs-traditie-talent-si-emotia-autentica-a-folclorului-la-vanju-mare/"],
   ["Recurring", "Split producer and distributor identity", "Route to market",
    "Domeniile Vînju Mare acts as sole distributor for the wines produced by Vie Vin Vânju Mare",
    "Separating the consumer-facing name from the production company lets the brand be marketed without the industrial history attached.",
    "https://domeniilevinjumare.ro/domeniile-vinju-mare/"],
   ["Recurring", "VINVEST and Vinul.ro excellence awards", "Awards / reputation",
    "Golds at the VINVEST national competition in Timișoara and Vinul.ro excellence awards for the Emissarius range",
    "Domestic competitions are worked rather than international ones, which matches a portfolio sold largely at home.",
    "https://www.crameromania.ro/crame/crama-vinju-mare-73.html"],
   ["Recurring", "Princely brand naming — Prințul Vlad, Vinul Principelui", "Portfolio marketing",
    "Flagship ranges named for a prince, alongside Lacrimă de Soare and the premium Emissarius",
    "Historical-authority naming substitutes for an estate story in a region whose modern reputation is still being built.",
    "https://domeniilevinjumare.ro/"],
   ["Recurring", "Plaiurile Drâncei red-wine terroir claim", "Terroir claim",
    "The area is positioned as the heart of Romanian red-wine country; before 1989 its reds were used to colour export blends",
    "Turns an unglamorous industrial past — bulk colouring wine — into evidence of concentration and ripeness.",
    "https://vvm.ro/"]],
 "people": [],
 "takeaway": ["No open role found. Recruitment presence is a BestJobs employer profile under the producing company; neither official site carries a careers route.",
   "Local festival heritage, princely brand naming and domestic competition awards, sold through a separate distribution identity",
   "Festivalul Viei și Vinului 2026; VINVEST and Vinul.ro awards; Prințul Vlad and Emissarius ranges; Plaiurile Drâncei terroir claim",
   "https://domeniilevinjumare.ro/",
   "Campaign evidence is regional and largely undated. No commercial staff are named in public sources."],
},
{
 "name": "Licorna WineHouse",
 "members": None,
 "bestjobs": ("https://www.bestjobs.eu/company-profile/licorna-winehouse", 1),
 "site": "https://www.licornawinehouse.ro/",
 "dept_note": "No LinkedIn capture available; BestJobs employer profile lists 1 alumnus (checked 2026-08-21)",
 "ceo": ["Virgil Harabagiu", "Owner",
   "Owner of the Gura Vadului estate opened in its present form in 2013, working about 30 hectares in Dealu Mare around a restored 1907–1909 manor house.",
   "Bachelor: not found. Master: not found. PhD: not found.",
   "Ownership; wine estate development; wine tourism; heritage restoration.",
   "https://www.crameromania.ro/crame/crama-harabagiu-licorna-winehouse-serafim-62.html",
   "Medium-high confidence on ownership; no CEO or general-manager title is published. Oenologist Florin-Gabriel Lăcureanu is the named technical lead."],
 "positions": [
   ["No dedicated vacancy page located", "Website review", "—", "No website listing found",
    f"Official website checked {CHECK}",
    "The site serves winery, shop, awards and tourism sections with no careers or vacancy route.",
    "https://www.licornawinehouse.ro/"],
   ["BestJobs employer profile (1 alumnus)", "Job-board review", "Gura Vadului, Prahova",
    "Employer profile active; no open role visible at check", f"BestJobs company profile checked {CHECK}",
    "Thin public recruitment footprint, consistent with a 30-hectare estate. No live listing was visible at check.",
    "https://www.bestjobs.eu/company-profile/licorna-winehouse"]],
 "campaigns": [
   ["2018", "Decanter gold for Bon Viveur 2014", "Awards / reputation",
    "The only Romanian red to take gold at that Decanter edition, with silvers for Serafim Fetească Neagră 2015 and Tămâioasă Românească 2016",
    "One outsized medal for a small estate becomes the permanent headline; the awards page exists to keep it working.",
    "https://vinul.ro/aur-decanter-licorna-winehouse-in-fruntea-plutonului-dealu-mare.html"],
   ["Recurring", "Awards page as a standing proof point", "Awards / reputation",
    "A dedicated Premii section collects international results in one place on the winery's own site",
    "Small producers cannot buy reach, so the site is built to make the medals do the persuading.",
    "https://www.licornawinehouse.ro/premii/"],
   ["Recurring", "Wine tourism at the restored Nicolau manor", "Experiential / tourism",
    "Tasting days at the 1907–1909 stone manor built by Italian craftsmen, part of the Gura Vadului complex",
    "The building supplies the heritage the 2013 winery itself does not have.",
    "https://www.taradacilor.ro/2026/03/16/licorna-winehouse-intre-legenda-si-realitate-o-zi-de-degustare-de-vinuri-in-dealu-mare/"],
   ["Recurring", "Named ranges — Serafim, Bon Viveur, Anno, Anno 5, Stih", "Portfolio marketing",
    "Five lines spanning event wines through to the premium reds and a dessert range",
    "Range names carry the tiering, so the estate name stays single and the medal halo travels across it.",
    "https://www.licornawinehouse.ro/shop2/"],
   ["Recurring", "Asociația Dealu Mare membership", "Trade / region",
    "Listed member of the Dealu Mare producers' association, promoted collectively with neighbouring estates",
    "Collective regional marketing is the affordable route to visibility for a producer this size.",
    "https://dealu-mare.ro/licorna/?lang=en"]],
 "people": [],
 "takeaway": ["No open role found. Recruitment presence is a BestJobs employer profile with a single alumnus; the official site carries no careers route.",
   "A single outsized Decanter result worked hard, supported by manor-house wine tourism and collective regional promotion",
   "Decanter 2018 gold for Bon Viveur; standing awards page; Nicolau manor tastings; Serafim and Anno ranges; Asociația Dealu Mare",
   "https://www.licornawinehouse.ro/premii/",
   "Award evidence is strong but dated; recent campaign activity is thin in public sources. No commercial staff are named."],
},
{
 "name": "Gitana Winery",
 "members": None,
 "bestjobs": (None, None),
 "site": "https://www.gitanawinery.com/en/",
 "dept_note": "Moldovan producer — outside the Romanian LinkedIn capture. Four staff are named on the winery's own People page (checked 2026-08-21)",
 "ceo": ["Petru Dulgher", "Owner (with Svetlana Dulgher, co-owner)",
   "Family owner of the Plopi estate in the Cantemir district, founded in 1999 on a 1953 winery and grown to roughly 360–390 hectares and 700,000 bottles a year, with Romania taking about 60% of output.",
   "Bachelor: not found. Master: not found. PhD: not found.",
   "Viticulture; family ownership; wine production; export to Romania, Europe, Asia and the USA.",
   "https://www.gitanawinery.com/en/people/",
   "High confidence: the winery publishes its own People page naming the family and their roles. Moldovan producer, listed here because Romania is its principal market."],
 "positions": [
   ["No dedicated vacancy page located", "Website review", "—", "No website listing found",
    f"Official website checked {CHECK}",
    "The site serves wines, history, people and contact sections with no careers or vacancy route.",
    "https://www.gitanawinery.com/en/"],
   ["Team published on the official People page", "Website review", "Plopi, Cantemir (Moldova)",
    "Four roles named; no vacancy advertised", f"Official People page checked {CHECK}",
    "Owner, co-owner, production and development manager and marketing and sales manager are named with titles — an unusual level of public disclosure for a winery this size.",
    "https://www.gitanawinery.com/en/people/"]],
 "campaigns": [
   ["2009", "Creation of the Gitana trademark", "Brand platform launch",
    "A symbolic brand built to represent the winery's wines, marking a new stage after the 1999 refounding",
    "A deliberate move from producing wine to owning a name — the step that made export listings possible.",
    "https://www.gitanawinery1953.com/our-history/"],
   ["Recurring", "Romania-first commercial model", "Route to market",
    "About 60% of production is sold in Romania, across supermarket retail and HoReCa in parallel",
    "A Moldovan producer treating Romania as home market rather than export changes what the marketing has to do: it competes on shelf, not on novelty.",
    "https://www.orange.ro/info/news/zf/article/582674"],
   ["Recent", "Lupi and La petite Sophie launches", "Product launch",
    "A new red and a new white positioned as future flagships for the house",
    "New flagships are launched under the existing trademark rather than as separate brands, keeping the equity in one name.",
    "https://wineofmoldova.com/en/gitana-winery/"],
   ["Recurring", "Wine of Moldova country programme", "Trade / export",
    "Listed producer within Moldova's national wine brand programme",
    "Borrows a state-funded country brand for credibility in markets where the producer name means little.",
    "https://wineofmoldova.com/en/gitana-winery/"],
   ["Recurring", "Family named publicly as the brand", "Brand storytelling",
    "Owner, co-owner and both daughters are named with their roles on the winery's own site",
    "Publishing the family is the authenticity claim; it is also what makes the commercial roster traceable at all.",
    "https://www.gitanawinery.com/en/people/"]],
 "people": [
   ["Lilia Dulgher", "Marketing", "Marketing & Sales Manager", "Marketing Leadership", "Leadership",
    "https://www.gitanawinery.com/en/people/"],
   ["Sergiu Matei", "Sales", "Area Sales Manager", "Regional / Area Sales", "Manager",
    "https://www.linkedin.com/in/sergiu-matei-2635b61ba/"]],
 "takeaway": ["No open role found. The winery publishes a People page naming four roles but advertises no vacancy and has no careers section.",
   "A trademark-led family house selling Romania-first, with new flagships launched under one name and the Moldovan country brand behind it",
   "Gitana trademark (2009); Romania-first retail and HoReCa model; Lupi and La petite Sophie launches; Wine of Moldova programme",
   "https://www.gitanawinery.com/en/",
   "Moldova-based producer, included because Romania is its main market — not a Romanian winery. Roles come from the winery's own People page, so confidence is high but the roster is small by construction."],
},
{
 "name": "Domeniile Sâmburești",
 "members": None,
 "bestjobs": ("https://www.bestjobs.eu/company-profile/viti-pomicola-samburesti", 2),
 "site": "https://samburesti.com/en/",
 "dept_note": "No LinkedIn capture available; BestJobs employer profile lists 2 alumni (checked 2026-08-21)",
 "ceo": ["Jean Valvis", "Majority owner (79%), Valvis Holding",
   "Greek-Swiss entrepreneur behind Dorna, LaDorna and Aqua Carpatica who invested in SC Viti-Pomicola Sâmburești from 2005–2006 and launched the Château Valvis, Domeniile Sâmburești and Sâmburel de Olt brands in 2009; has said the wine brands will stay in the family.",
   "Bachelor: not found. Master: not found. PhD: not found.",
   "FMCG brand building; mineral water; dairy; investment; wine ownership.",
   "https://www.zfcorporate.ro/retail-agrobusiness/jean-valvis-brandurile-aqua-carpatica-domeniile-samburesti-si-chateau-valvis-vor-ramane-in-familie-13779208",
   "High confidence on ownership and brand launches. Day-to-day leadership sits with executive director Ioan Manea; winemaker is Manuel Nica."],
 "positions": [
   ["No dedicated vacancy page located", "Website review", "—", "No website listing found",
    f"Official website checked {CHECK}",
    "The site serves collections, history and contact sections with no careers or vacancy route.",
    "https://samburesti.com/en/"],
   ["BestJobs employer profile (2 alumni)", "Job-board review", "Dobroteasa, Olt",
    "Employer profile active; no open role visible at check", f"BestJobs company profile checked {CHECK}",
    "Listed under the producing company, Viti-Pomicola Sâmburești. No live listing was visible at check.",
    "https://www.bestjobs.eu/company-profile/viti-pomicola-samburesti"]],
 "campaigns": [
   ["2024", "Best national producer of the year", "Awards / reputation",
    "Viti-Pomicola Sâmburești took the national producer title with two gold-medal wines",
    "A producer-level title does for a portfolio what a single medal cannot — it licenses the claim across every label.",
    "https://samburesti.com/domeniile-samburesti-cel-mai-bun-producator-national-al-anului-2024/"],
   ["2024–2025", "Carpathia and ALAI line launches", "Product launch",
    "Two new quality lines added to a portfolio that already ran Château Valvis, Domeniile Sâmburești and Sâmburel de Olt",
    "Extends upward and sideways at once, which is how a three-tier portfolio absorbs a producer-of-the-year claim.",
    "https://samburesti.com/en/colectii/carpathia/"],
   ["Recurring", "Carpathia at Miss România", "Sponsorship / prestige",
    "The premium Carpathia line presented in a beauty-and-style setting built around Romanian elegance",
    "Places a premium wine in a non-wine prestige context, reaching an audience trade fairs do not.",
    "https://samburesti.com/en/colectii/carpathia/"],
   ["Recurring", "Château Valvis founder-brand halo", "Brand architecture",
    "The flagship carries the owner's own name, already known nationally from Dorna, LaDorna and Aqua Carpatica",
    "Borrows FMCG brand equity built in water and dairy — a shortcut no purely viticultural producer has.",
    "https://samburesti.com/en/colectii/chateau-valvis/"],
   ["2026", "Vinalies Internationales 2026", "Awards / reputation",
    "Named among the Romanian producers medalled at the edition, in which Romania took 27 medals in total",
    "Keeps an international result on the board in the year after the national producer title.",
    "https://winesofromania.com/vinalies-internationales-2026-medalii-romania/"]],
 "people": [],
 "takeaway": ["No open role found. Recruitment presence is a BestJobs employer profile with 2 alumni under the producing company.",
   "An FMCG owner's playbook: a founder-named flagship, upward line extensions and prestige placements, backed by a national producer-of-the-year title",
   "Best national producer 2024; Carpathia and ALAI launches; Carpathia at Miss România; Château Valvis; Vinalies 2026",
   "https://samburesti.com/en/",
   "Ownership and campaign evidence are strong. No marketing or sales staff are named in public sources, so the roster is empty rather than estimated."],
},
{
 "name": "Crama Rasova",
 "members": None,
 "bestjobs": ("https://www.bestjobs.eu/company-profile/crama-rasova", 4),
 "site": "https://www.cramarasova.ro/",
 "dept_note": "No LinkedIn capture available; BestJobs employer profile lists 4 alumni (checked 2026-08-21)",
 "ceo": ["Zoe Ghiuri", "Co-founder and owner (with Dumi and George Ghiuri)",
   "Co-founder of the Dealul Vifor estate near Cernavodă, an investment of more than 8 million euro that pairs a Dobrogea vineyard with a concert and tasting venue on the Danube's high bank.",
   "Bachelor: not found. Master: not found. PhD: not found.",
   "Ownership; wine estate development; hospitality and events; wine tourism.",
   "https://www.desprevin.ro/cunoaste-o-mai-bine-zoe-ghiuri-co-fondator-crama-rasova",
   "High confidence on co-founder status; no CEO title is published. Răzvan Macici, formerly of Nederburg in South Africa, is the winemaker and the public quality signature."],
 "positions": [
   ["No dedicated vacancy page located", "Website review", "—", "No website listing found",
    f"Official website checked {CHECK}",
    "The site is an e-commerce and events platform with no careers or vacancy section.",
    "https://www.cramarasova.ro/"],
   ["BestJobs employer profile (4 alumni)", "Job-board review", "Cernavodă, Constanța",
    "Employer profile active; no open role visible at check", f"BestJobs company profile checked {CHECK}",
    "No live listing was visible in the page served at check.",
    "https://www.bestjobs.eu/company-profile/crama-rasova"]],
 "campaigns": [
   ["Recurring", "AER / AER LIBER concert series", "Experiential / events",
    "Ticketed mini-festival evenings at the winery — 250 lei a head — with Smiley, Loredana, Vama and The Motans on the bill",
    "The event is a product with its own price and phone line, not a promotion: the winery sells attendance as well as wine.",
    "https://www.cramarasova.ro/aer-liber-by-crama-rasova.html"],
   ["May 2025", "„Acasă la vin” with Unvinpezi.ro", "Retail partnership",
    "Order-and-win mechanic running 7–25 May 2025; ten winners taken to a guided tasting with blind-tasting world champion Valentin Ceafalău",
    "Buys a specialist retailer's audience and an expert's authority in one move, with the prize itself a winery visit.",
    "https://playtech.ro/2025/acasa-la-vin-by-unvinpezi-ro-ajunge-in-dobrogea-la-crama-rasova/"],
   ["Recurring", "Răzvan Macici as the quality signature", "Winemaker-led reputation",
    "New releases are communicated as wines signed by Răzvan Macici, whose career includes senior winemaking in South Africa",
    "A named winemaker carries reputation across a young estate faster than the estate name can earn it.",
    "https://winesofromania.com/en/wineries/the-rasova-winery/"],
   ["Recurring", "Creația and Recreația brand split", "Portfolio marketing",
    "A serious range beside a playful one — La Plage, Craft, Riviera Sur Mer, Nud, Tortuga, Imperfect, Aripi and Dulce Nebunie",
    "Two registers under one roof let the concert audience and the fine-wine audience each be sold something in their own language.",
    "https://www.cramarasova.ro/creatia.html"],
   ["Recurring", "Own shop, tours and the Rasova&Friends club", "Wine tourism / DTC",
    "Direct e-commerce with free delivery over 299 lei, alongside tastings, tours, gift packs and a partner club",
    "Direct sales and events reinforce each other: the visit sells the wine and the wine sells the next visit.",
    "https://www.cramarasova.ro/"]],
 "people": [],
 "takeaway": ["No open role found. Recruitment presence is a BestJobs employer profile with 4 alumni; the site is commerce and events only.",
   "A destination winery: ticketed concerts on the Danube, a named star winemaker, a split serious-and-playful portfolio and direct e-commerce",
   "AER / AER LIBER concert series; Acasă la vin with Unvinpezi.ro (2025); Răzvan Macici releases; Creația vs Recreația ranges; Rasova&Friends",
   "https://www.cramarasova.ro/",
   "Campaign evidence is unusually rich and self-published. No marketing or sales staff are named in public sources."],
},
{
 "name": "Liliac Winery",
 "members": None,
 "bestjobs": ("https://www.bestjobs.eu/company-profile/amb-wine-company", 15),
 "site": "https://www.liliac.com/",
 "dept_note": "No LinkedIn capture available; BestJobs employer profile for amb Wine Company lists 15 alumni (checked 2026-08-21)",
 "ceo": ["Miron Radić", "CEO / General Manager, amb Wine Company",
   "Marketing man by training who joined founder Alfred Michael Beck's AMB Holding, ran Liliac's marketing and sales from 2015 and took over as general director of the operating company in 2018; has led a 3.4 million euro expansion and the move into wine tourism with accommodation.",
   "Bachelor/equivalent: Business Administration — Marketing and Production Management, Vienna University of Economics and Business, with a diploma thesis on Romanian wines. Master: not found. PhD: not found.",
   "Marketing; sales; wine business management; hospitality and wine tourism.",
   "https://www.desprevin.ro/cunoaste-l-mai-bine-pe-miron-radic-general-manager-crama-liliac",
   "High confidence on role, tenure and education; the education detail is unusually well documented for this set."],
 "positions": [
   ["No dedicated vacancy page located", "Website review", "—", "No website listing found",
    f"Official website checked {CHECK}",
    "The site serves wines, estate and visit sections with no careers or vacancy route.",
    "https://www.liliac.com/"],
   ["BestJobs employer profile (15 alumni)", "Job-board review", "Batoș, Mureș / Bucharest",
    "Employer profile active; no open role visible at check", f"BestJobs company profile checked {CHECK}",
    "Listed under the operating company, amb Wine Company — the largest public recruitment footprint among the wineries added here after Crama Ceptura.",
    "https://www.bestjobs.eu/company-profile/amb-wine-company"]],
 "campaigns": [
   ["Recurring", "„Tandem” with Castel Mimi", "Partnership / co-branding",
    "Collaboration wines between Liliac in Romania and Castel Mimi in Moldova, founded on the two general managers' friendship",
    "A cross-border co-brand turns a personal relationship into a product, and gives each winery access to the other's market story.",
    "https://business-review.eu/profiles1/interviews-interviews/tandem-interview-with-miron-radic-ceo-liliac-and-adrian-trofim-gm-castel-mimi-253838"],
   ["2021–2025", "3.4 million euro expansion and tourism lodge", "Wine tourism / investment",
    "Winery modernisation plus accommodation services at the Batoș lodge overlooking the hills",
    "Capacity and hospitality are built together, so the investment story doubles as a destination story.",
    "https://www.economica.net/miron-radic-ceo-crama-liliac-efectele-schimbarilor-climatice-ne-au-ajutat-sa-producem-vin-rosu-pe-care-nu-l-puteam-face-inainte-servicii-turistice-crama_712872.html"],
   ["Recurring", "„The guardian of Transylvanian wine”", "Brand platform",
    "The bat emblem and an explicit claim on Transylvania as the brand's territory",
    "Owning a region rather than a village gives a 2010 winery a story with the scale of a much older one.",
    "https://www.liliac.com/"],
   ["Recurring", "CEO-led business-press presence", "PR / thought leadership",
    "Repeated interviews positioning Liliac within a growing Romanian boutique-winery segment and discussing climate effects on red-wine production",
    "The general manager is used as the brand's spokesperson, which is cheap reach for a winery of this size.",
    "https://business-review.eu/news/interview-miron-radic-liliac-winery-more-and-more-boutique-wineries-like-us-are-coming-to-the-market-158448"],
   ["Recurring", "Tiered labels — Liliac, Private Selection, Crepuscul, TITAN", "Portfolio marketing",
    "Four named tiers across roughly 52 hectares in Batoș and Lechința",
    "A narrow estate is made to cover several price points without diluting the single Transylvanian claim.",
    "https://premiumwinesofromania.com/liliac/"]],
 "people": [],
 "takeaway": ["No open role found. Recruitment presence is a BestJobs employer profile with 15 alumni under amb Wine Company.",
   "A region-owning brand platform run by a marketing-trained CEO, worked through cross-border collaboration, tourism investment and business-press presence",
   "Tandem with Castel Mimi; 3.4 m euro expansion and lodge; guardian-of-Transylvania platform; CEO interviews; tiered labels",
   "https://www.liliac.com/",
   "Leadership evidence including education is strong. Beyond the CEO, no marketing or sales staff are named in public sources."],
},
{
 "name": "Crama Oprișor",
 "members": None,
 "bestjobs": ("https://www.bestjobs.eu/company-profile/carl-reh-winery", None),
 "site": "https://www.crama-oprisor.com/",
 "dept_note": "No LinkedIn capture available; the winery publishes a full team page naming 14 staff, and a BestJobs employer profile exists (checked 2026-08-21)",
 "ceo": ["Gabriel Roceanu", "General Manager, Carl Reh Winery / Crama Oprișor",
   "General manager of the Romanian operation of Reh Kendermann GmbH of Bingen am Rhein, which established Carl Reh Winery in 1997, took over the Oprișor winery in 2000, replanted 250 hectares and adopted the Crama Oprișor name for the Romanian market in 2008.",
   "Bachelor: not found. Master: not found. PhD: not found.",
   "General management; wine production; German-owned subsidiary leadership; branded portfolio.",
   "https://www.crama-oprisor.com/about_us_team.html",
   "High confidence: the general manager and the full commercial team are published with titles and direct e-mail addresses on the winery's own site."],
 "positions": [
   ["No dedicated vacancy page located", "Website review", "—", "No website listing found",
    f"Official website checked {CHECK}",
    "The site publishes a full named team with contact addresses but no careers or vacancy section.",
    "https://www.crama-oprisor.com/about_us_team.html"],
   ["BestJobs employer profile", "Job-board review", "Oprișor, Mehedinți / Bucharest",
    "Employer profile active; no open role visible at check", f"BestJobs company profile checked {CHECK}",
    "Listed under the legal entity, Carl Reh Winery. No live listing was visible at check.",
    "https://www.bestjobs.eu/company-profile/carl-reh-winery"]],
 "campaigns": [
   ["2015–2024", "Premiile Crama Oprișor pentru Desen Contemporan", "Arts patronage",
    "A contemporary-drawing prize initiated by Ciprian Paleologu in 2015, run with UNArte Bucharest (2016–17), UAD Cluj-Napoca (2021–22) and the National Museum of Contemporary Art; 6,000 euro prize fund for artists up to 35",
    "Patronage rather than sponsorship: the winery runs the institution's competition, which buys a cultural standing advertising cannot.",
    "https://crama-oprisor.ro/premiile/despre-premii/"],
   ["2008", "Adoption of the Crama Oprișor name", "Brand repositioning",
    "German-owned Carl Reh Winery began presenting itself on the Romanian market under a Romanian place name",
    "A foreign owner buying local legitimacy by putting the village, not the parent company, on the label.",
    "https://www.crama-oprisor.com/about_us_history_past.html"],
   ["Recurring", "La Cetate as the flagship", "Portfolio marketing",
    "The upper-segment label built around winemaker Veronica Gheorghiu's work",
    "A single named flagship gives an otherwise broad German-owned portfolio a critical anchor.",
    "https://www.crama-oprisor.com/wines_series.html?concept=Carl+Reh+Winery&gama=LA+CETATE"],
   ["Recurring", "Romanian folklore brand naming", "Portfolio marketing",
    "Măiastru, Caloian, Rusalcă Albă, Cupola Sanctis and Smerenie alongside Val Duna and Dragaica Roșie",
    "Every range name is drawn from Romanian myth or ritual — the same localisation strategy as the 2008 rename, applied to the shelf.",
    "https://www.crameromania.ro/crame/crama-oprisor-38.html"],
   ["Recurring", "Named regional sales team published with contacts", "Trade-facing transparency",
    "A national sales manager and seven regional managers, including a dedicated HoReCa role, listed with direct e-mail addresses",
    "Publishing the commercial team is itself a trade proposition: buyers can reach the right person without going through a switchboard.",
    "https://www.crama-oprisor.com/about_us_team.html"]],
 "people": [
   ["Luminița Tzakis", "Sales", "National Sales Manager", "National Sales", "Leadership",
    "https://www.crama-oprisor.com/about_us_team.html"],
   ["Gabriel Cristea", "Sales", "Regional Sales Manager — South-East", "Regional / Area Sales", "Manager",
    "https://www.crama-oprisor.com/about_us_team.html"],
   ["Florin Ionescu", "Sales", "Regional Sales Manager — North-West", "Regional / Area Sales", "Manager",
    "https://www.crama-oprisor.com/about_us_team.html"],
   ["Iliuță Cucu", "Sales", "Regional Sales Manager — HoReCa", "HoReCa / On-Trade", "Manager",
    "https://www.crama-oprisor.com/about_us_team.html"],
   ["Horațiu Negru", "Sales", "Regional Sales Manager — Centre / Transylvania", "Regional / Area Sales", "Manager",
    "https://www.crama-oprisor.com/about_us_team.html"],
   ["Roxana Ferchiu", "Sales", "Regional Sales Manager — East", "Regional / Area Sales", "Manager",
    "https://www.crama-oprisor.com/about_us_team.html"],
   ["Alexandra Ciungu", "Sales", "Regional Sales Manager — Oltenia", "Regional / Area Sales", "Manager",
    "https://www.crama-oprisor.com/about_us_team.html"],
   ["Cătălin Șimon", "Sales", "Regional Sales Manager", "Regional / Area Sales", "Manager",
    "https://www.crama-oprisor.com/about_us_team.html"]],
 "takeaway": ["No open role found. The winery publishes a full named team with direct contacts but no careers page; a BestJobs employer profile exists under Carl Reh Winery.",
   "Cultural patronage and thorough localisation: a museum-partnered art prize, a Romanian place name over a German parent, and folklore-derived range names",
   "Premiile Crama Oprișor pentru Desen Contemporan; 2008 rename; La Cetate flagship; folklore brand naming; published sales team",
   "https://www.crama-oprisor.com/",
   "The strongest publicly documented commercial roster of any winery added here — eight sales roles including a dedicated HoReCa manager, all from the winery's own team page. No marketing role is published."],
},
{
 "name": "Domeniile Săhăteni",
 "members": None,
 "bestjobs": ("https://www.bestjobs.eu/company-profile/domeniile-sahateni", 11),
 "site": "https://aureliavisinescu.com/",
 "dept_note": "No LinkedIn capture available; BestJobs employer profile lists 11 alumni (checked 2026-08-21)",
 "ceo": ["Aurelia Vișinescu", "Founder and winemaker",
   "Oenologist who founded Domeniile Săhăteni in 2003 with her cousin by marriage Steve Cacenco and built it to 82 hectares across Săhăteni, Năeni and Fințești with a cellar handling about 1,000 tonnes of grapes a season; the winery trades under her own name.",
   "Bachelor/equivalent: oenology (institution not stated in reviewed sources). Master: not found. PhD: not found.",
   "Oenology; winemaking; estate founding; small-batch premium production.",
   "https://winesofromania.com/en/aurelia-visinescu-sahateni-domains/",
   "High confidence on founder, role and estate detail; the exact degree and institution are not stated in the sources reviewed."],
 "positions": [
   ["No dedicated vacancy page located", "Website review", "—", "No website listing found",
    f"Official website checked {CHECK}",
    "The site serves wines, story and contact sections with no careers or vacancy route.",
    "https://aureliavisinescu.com/"],
   ["BestJobs employer profile (11 alumni)", "Job-board review", "Săhăteni, Buzău / Bucharest",
    "Employer profile active; no open role visible at check", f"BestJobs company profile checked {CHECK}",
    "Listed under Domeniile Sahateni. No live listing was visible at check.",
    "https://www.bestjobs.eu/company-profile/domeniile-sahateni"]],
 "campaigns": [
   ["2003 onward", "Winemaker-name masterbrand", "Brand platform",
    "The winery trades publicly as Aurelia Vișinescu — Domeniile Săhăteni, putting the founding oenologist's name above the estate's",
    "Rare in Romanian wine: the person is the brand, which makes every critical mention of the winemaker also a brand mention.",
    "https://aureliavisinescu.com/"],
   ["Recurring", "Channel-segmented brand architecture", "Portfolio marketing",
    "Nomad as the general line, Artisan, Karakter and Anima built for HoReCa, and Promessa, Etika, Distinct and Genesa for retail",
    "The portfolio is split by where it sells rather than by grape or price, which keeps restaurant and supermarket listings from competing.",
    "https://www.crameromania.ro/crame/sahateni-aurelia-visinescu-crama-10.html"],
   ["Recurring", "Small-batch, story-named wines", "Product storytelling",
    "Lots of 2,500 to 20,000 bottles, monovarietal and blends, with names chosen to carry a story",
    "Scarcity plus narrative is the argument a producer makes when it cannot compete on volume or price.",
    "https://winesofromania.com/en/aurelia-visinescu-sahateni-domains/"],
   ["Recurring", "Asociația Dealu Mare membership", "Trade / region",
    "Listed member of the Dealu Mare producers' association and promoted collectively",
    "Regional collective marketing at the appellation level, alongside the personal brand.",
    "https://dealu-mare.ro/aurelia-visinescu/?lang=en"],
   ["Recurring", "Winery as a gastronomic destination", "Wine tourism",
    "The Săhăteni cellar is presented and listed as a visitable place with food-and-wine experiences",
    "Visits convert the personal brand into something people can meet, which is the point of naming a winery after a person.",
    "https://go-mio.ro/crama/domeniile-sahateni---aurelia-visinescu"]],
 "people": [],
 "takeaway": ["No open role found. Recruitment presence is a BestJobs employer profile with 11 alumni.",
   "A winemaker-as-brand house with the portfolio split by sales channel rather than by tier, plus small-batch storytelling and regional collective promotion",
   "Aurelia Vișinescu masterbrand; Nomad / Artisan / Karakter / Anima HoReCa split; Promessa and Etika retail lines; Asociația Dealu Mare; cellar visits",
   "https://aureliavisinescu.com/",
   "Brand architecture is well documented; dated campaign activity for 2025–2026 was not found in public sources. No marketing or sales staff are named apart from the founder."],
},
{
 "name": "Crama 1000 de Chipuri",
 "members": None,
 "bestjobs": ("https://www.bestjobs.eu/company-profile/1000-de-chipuri", 2),
 "site": "https://1000dechipuri.ro/",
 "dept_note": "No LinkedIn capture available; BestJobs employer profile lists 2 alumni (checked 2026-08-21)",
 "ceo": ["Ștefan Ionescu", "Founder and owner",
   "Founder of the Urlați estate whose first harvest was 2011 and first wines 2012; works 64 hectares, bottles about 120,000 wines a year entirely for HoReCa, and is investing 2 million euro in a new winery to reach roughly 200,000 bottles.",
   "Bachelor: not found. Master: not found. PhD: not found.",
   "Entrepreneurship; viticulture; HoReCa distribution; wine tourism.",
   "https://www.zf.ro/business-construct/zf-live-stefan-ionescu-proprietarul-cramei-1000-de-chipuri-investim-21764157",
   "High confidence on founder, ownership and production detail from business-press interviews."],
 "positions": [
   ["No dedicated vacancy page located", "Website review", "—", "No website listing found",
    f"Official website checked {CHECK}",
    "The site serves wines and visit information with no careers or vacancy route.",
    "https://1000dechipuri.ro/"],
   ["BestJobs employer profile (2 alumni)", "Job-board review", "Urlați, Prahova",
    "Employer profile active; no open role visible at check", f"BestJobs company profile checked {CHECK}",
    "No live listing was visible in the page served at check.",
    "https://www.bestjobs.eu/company-profile/1000-de-chipuri"]],
 "campaigns": [
   ["2012 onward", "The „1000 de chipuri” naming concept", "Brand platform",
    "Each wine carries the name and image of the person the winery bought that parcel of land from, as a mark of respect",
    "The brand name is the mechanic: every label is a person, so the portfolio cannot be extended without acquiring another story.",
    "https://www.crameromania.ro/crame/crama-1000-de-chipuri-215.html"],
   ["Recurring", "„Vinul tău din via ta”", "Consumer / DTC programme",
    "A programme letting customers take on a plot and receive the wine made from it, framed as restoring the link between people and the land",
    "Turns the founding story into a service, and creates a customer relationship that outlasts a single purchase.",
    "https://hotnews.ro/interviu-drink-insider-cu-stefan-ionescu-crama-1000-de-chipuri-proiectul-vinul-tau-din-via-ta-ncearca-sa-refaca-legatura-cu-pamntul-adica-le-35760"],
   ["Recurring", "HoReCa-only distribution", "Route to market",
    "All 120,000 bottles go to restaurants and hotels; the wines are not sold through grocery retail",
    "Deliberate scarcity on the shelf: the wine is only met where someone can explain it.",
    "https://www.zf.ro/business-construct/zf-live-stefan-ionescu-proprietarul-cramei-1000-de-chipuri-investim-21764157"],
   ["2024–2026", "2 million euro new winery", "Corporate growth",
    "A new facility intended to take output to about 200,000 bottles a year",
    "Growth is planned without leaving the HoReCa channel, which is the harder of the two ways to scale.",
    "https://www.zf.ro/business-construct/zf-live-stefan-ionescu-proprietarul-cramei-1000-de-chipuri-investim-21764157"],
   ["Recurring", "Three collections — Sforile/Fințești, Via Mirabilis, 1000 de chipuri", "Portfolio marketing",
    "Twenty labels grouped into three collections across 64 hectares",
    "Collections give a single-estate producer enough structure to hold a restaurant list on its own.",
    "https://1000dechipuri.ro/"]],
 "people": [],
 "takeaway": ["No open role found. Recruitment presence is a BestJobs employer profile with 2 alumni.",
   "A naming concept that doubles as the brand story, extended into a plot-adoption programme and defended by HoReCa-only distribution",
   "1000 de chipuri portrait labels; Vinul tău din via ta; HoReCa-only route to market; 2 m euro winery expansion; three collections",
   "https://1000dechipuri.ro/",
   "Founder and business evidence is strong from business-press interviews. No marketing or sales staff are named in public sources."],
},
{
 "name": "Casa de Vinuri Negrini",
 "members": None,
 "bestjobs": ("https://www.bestjobs.eu/company-profile/casa-de-vinuri-negrini", None),
 "site": "https://www.negrini.ro/",
 "dept_note": "No LinkedIn capture available; BestJobs employer profile exists, alumni count not published (checked 2026-08-21)",
 "ceo": ["Cristina Viorica Negrini Gheorghe", "Founder",
   "Founded the wine house in 1990 by buying one of Drăgășani's most valuable vineyards, the former estate of General Teodrini — ten hectares of which seven are vines — and replanted it with Fetească Regală, Sauvignon Blanc and Merlot.",
   "Bachelor: not found. Master: not found. PhD: not found.",
   "Ownership; vineyard acquisition and replanting; branded wine production.",
   "https://www.crameromania.ro/crame/negrini-casa-vinuri-2.html",
   "Medium confidence: the founder is named in producer directories, but no current CEO or general-manager title is published."],
 "positions": [
   ["No dedicated vacancy page located", "Website review", "—", "No website listing found",
    f"Official website checked {CHECK}",
    "The site serves brand and product information with no careers or vacancy route.",
    "https://www.negrini.ro/"],
   ["BestJobs employer profile", "Job-board review", "Drăgășani, Vâlcea / Bucharest",
    "Employer profile active; no open role visible at check", f"BestJobs company profile checked {CHECK}",
    "No live listing and no alumni count were visible in the page served at check.",
    "https://www.bestjobs.eu/company-profile/casa-de-vinuri-negrini"]],
 "campaigns": [
   ["Recurring", "The ballerina emblem", "Brand symbol",
    "The dancer on the label commemorates a family love story with an Italian ballerina and is presented as standing for elegance and passion",
    "A single owned symbol does the work of a range architecture — it is recognisable on shelf without reading the name.",
    "https://www.crameromania.ro/crame/negrini-casa-vinuri-2.html"],
   ["1990 onward", "General Teodrini estate provenance", "Heritage storytelling",
    "The winery is built on an interwar general's Drăgășani property, bought in 1990 and replanted",
    "Borrowed history: the estate's story predates the company by a century, which a 1990 founding otherwise could not claim.",
    "https://www.crameromania.ro/crame/negrini-casa-vinuri-2.html"],
   ["Recurring", "Negrini Premium retail line", "Portfolio marketing",
    "Sauvignon Blanc, Fetească Regală, Rosé, Cabernet Sauvignon, Merlot and Negru de Drăgășani listed by national grocers",
    "National grocery listings are the whole distribution story here, so the range is built to fill a shelf set rather than a wine list.",
    "https://carrefour.ro/produse/vin-alb-sec-negrini-premium-sauvignon-blanc-0-75l-19-10506412"],
   ["Recurring", "Hex range", "Portfolio marketing",
    "A second, differently styled label running alongside Premium",
    "A second name lets the house reach a different shelf position without discounting the first.",
    "https://realfoods.ro/vin-rose/7620-negrini-hex-rose.html"],
   ["Recurring", "Negru de Drăgășani as the local signature", "Terroir claim",
    "The indigenous Drăgășani red is carried as the range's distinguishing variety",
    "A variety few competitors list is the cheapest available point of difference in a national grocery set.",
    "https://www.negrini.ro/"]],
 "people": [],
 "takeaway": ["No open role found. Recruitment presence is a BestJobs employer profile with no published alumni count.",
   "A single owned symbol and a borrowed estate history, worked through national grocery listings rather than events or awards",
   "Ballerina emblem; General Teodrini estate provenance; Negrini Premium and Hex ranges; Negru de Drăgășani",
   "https://www.negrini.ro/",
   "The thinnest public evidence base of the wineries added here: no dated campaigns, no awards and no named staff beyond the founder were located."],
},
{
 "name": "Petro Vaselo",
 "members": None,
 "bestjobs": ("https://www.bestjobs.eu/company-profile/petro-vaselo", None),
 "site": "https://petrovaselo.com/en/",
 "dept_note": "No LinkedIn capture available; a BestJobs employer profile exists but is empty (checked 2026-08-21)",
 "ceo": ["Nello Dal Tio", "Owner (Dal Tio family)",
   "Head of the Italian family that founded the winery at Petrovaselo in 2002 to give an Italian reading of a 2,500-year-old Banat terroir; the estate holds 172 hectares of which 42 are certified-organic vineyard.",
   "Bachelor: not found. Master: not found. PhD: not found.",
   "Family ownership; organic viticulture; international investment in Romanian wine.",
   "https://petrovaselo.com/en/",
   "High confidence on ownership and founding. No CEO title is published; Marco Feltrin is the named oenologist."],
 "positions": [
   ["No dedicated vacancy page located", "Website review", "—", "No website listing found",
    f"Official website checked {CHECK}",
    "The site serves wines, estate and shop sections with no careers or vacancy route.",
    "https://petrovaselo.com/en/"],
   ["BestJobs employer profile (empty)", "Job-board review", "Petrovaselo, Timiș",
    "Profile exists but carries no company detail or alumni", f"BestJobs company profile checked {CHECK}",
    "The profile page served no company description, alumni count or live listing at check.",
    "https://www.bestjobs.eu/company-profile/petro-vaselo"]],
 "campaigns": [
   ["Recurring", "„La Petrovaselo în vie” running event", "Experiential / sport",
    "A vineyard running event with several race distances and tastings at the winery, held again in 2026",
    "Sport brings a non-wine audience onto the estate, which is a cheaper acquisition route than a tasting programme.",
    "https://calendar.sportic.ro/events/view?hash=279825f0d55ad8df598cdbdf5ed10724fbe6570e"],
   ["Recurring", "Certified organic viticulture", "Sustainability positioning",
    "Certified organic vineyard with two manual selections of every bunch before vinification",
    "Certification is a claim that survives without advertising, which suits a producer with no consumer media presence.",
    "https://www.blog.desprevin.ro/crama-petro-vaselo-pe-scurt-despre-experimentari-sustenabilitate-si-viticultura-biologica-in-banat/"],
   ["Recurring", "Bendis traditional-method sparkling family", "Product / portfolio",
    "Bendis Rose, Bendis Zenith and Bendis Nadir form a dedicated sparkling range under their own name",
    "A separately named sparkling family lets the estate compete in a category buyers shop apart from still wine.",
    "https://revino.ro/petro-vaselo-bendis-degustare-vin-banat-vizita-crama-a270.html"],
   ["2002 onward", "Italian founding story on a 2,500-year-old terroir", "Brand storytelling",
    "An Italian family's interpretation of an ancient Banat site, in the DOC Recaș appellation",
    "Foreign winemaking credentials plus deep local history is the standard argument for a region without an established fine-wine reputation.",
    "https://petrovaselo.com/en/"],
   ["Recurring", "Private and corporate events at the winery", "Wine tourism",
    "Tastings and organised events for personal and business groups",
    "Hospitality revenue and brand exposure from the same fixed asset.",
    "https://revino.ro/turism-viticol/crame/crama-pertro-vaselo-recas-degustari-vin-turism-viticol-enoturism-romania.html"]],
 "people": [],
 "takeaway": ["No open role found. A BestJobs employer profile exists but carries no company detail; the official site has no careers route.",
   "Organic certification and an Italian founding story, activated through a vineyard running event and winery hospitality rather than media",
   "La Petrovaselo în vie; organic certification; Bendis sparkling range; Dal Tio family story; winery events",
   "https://petrovaselo.com/en/",
   "Ownership and positioning are well evidenced; no dated campaign spend or awards detail was located. No commercial staff are named."],
},
{
 "name": "Carastelec Winery",
 "members": None,
 "bestjobs": ("https://www.bestjobs.eu/company-profile/carastelec-winery", None),
 "site": "https://winesofromania.com/en/wineries/carastelec-sparkling-winery/",
 "dept_note": "No LinkedIn capture available; BestJobs employer profile exists, alumni count not published (checked 2026-08-21)",
 "ceo": ["Csaba Bereczki", "Oenologist and senior technical lead",
   "Joined Carastelec straight from university in 2014 and is the winery's named technical lead. The winery itself was launched in 2011 by five entrepreneurs — three from Transylvania, two from Hungary — who invested more than 5 million euro, planting 22.4 hectares in 2011 and building the cellar over 2011–2012 with European funds.",
   "Bachelor/equivalent: oenology (institution not stated in reviewed sources). Master: not found. PhD: not found.",
   "Oenology; traditional-method sparkling wine production.",
   "https://cluj.com/articole/crama-de-pe-insula-cristalina-din-nord-vestul-transilvaniei-carastelec/",
   "Low-to-medium confidence as a leadership entry: no CEO, general manager or managing partner is publicly named, and the ownership group is described only collectively. The oenologist is recorded here as the only named senior figure."],
 "positions": [
   ["No dedicated vacancy page located", "Website review", "—", "No website listing found",
    f"Official website and producer profiles checked {CHECK}",
    "No careers or vacancy route was located on the winery's own or partner pages.",
    "https://winesofromania.com/en/wineries/carastelec-sparkling-winery/"],
   ["BestJobs employer profile", "Job-board review", "Carastelec, Sălaj",
    "Employer profile active; no open role visible at check", f"BestJobs company profile checked {CHECK}",
    "No live listing and no alumni count were visible in the page served at check.",
    "https://www.bestjobs.eu/company-profile/carastelec-winery"]],
 "campaigns": [
   ["2017–2024", "Champagne & Sparkling Wine World Championships", "Awards / reputation",
    "Medals at every edition since the 2017 launch: two silvers in 2017, gold for Carassia Blanc de Blancs and a Best in Class Future Release in 2018, and four golds in 2024",
    "A specialist competition rewards a specialist producer far more than a general one would — the whole reputation is built in one arena.",
    "https://start-up.ro/carastelec-crama-din-romania-care-castiga-campionatele-mondiale-de-spumante/"],
   ["2011 onward", "Romania's first dedicated sparkling-wine project", "Category positioning",
    "The winery was designed from the outset around sparkling and pétillant wine rather than still wine, with 22.4 hectares planted to varieties chosen for it",
    "Category ownership instead of range breadth: being first at one thing is the claim, and it dates from before the first bottle.",
    "https://winesofromania.com/en/wineries/carastelec-sparkling-winery/"],
   ["Recurring", "Three-brand ladder — Carassia, Friza, Vinca", "Portfolio marketing",
    "Traditional-method sparkling, pétillant and still ranges at three distinct price positions, with two-thirds of the roughly 150,000 bottles sparkling",
    "The ladder lets the championship medals sit on Carassia while Friza takes the volume.",
    "https://www.crameromania.ro/crame/crama-vinca-salaj-carastelec-166.html"],
   ["Recurring", "Traditional-method production claim", "Product claim",
    "Fermentation and maturation in bottle, communicated as the quality argument for Carassia",
    "Method is the argument sparkling buyers already understand, so it needs no education spend.",
    "https://revino.ro/crama-carastelec-a-lansat-o-noua-gama-de-spumante-carassia-metoda-traditionala-a375.html"]],
 "people": [],
 "takeaway": ["No open role found. Recruitment presence is a BestJobs employer profile with no published alumni count.",
   "Category ownership in sparkling wine, proved by repeat medals at one specialist world championship and sold through a three-brand ladder",
   "Champagne & Sparkling Wine World Championships 2017–2024; first dedicated sparkling project; Carassia / Friza / Vinca ladder; traditional-method claim",
   "https://winesofromania.com/en/wineries/carastelec-sparkling-winery/",
   "Awards evidence is strong. Leadership is the weakest entry in this set: no CEO or general manager is publicly named, only the ownership group and the oenologist. No commercial staff are named."],
},
{
 "name": "Domeniile Davidescu",
 "members": None,
 "bestjobs": (None, None),
 "site": "https://domeniiledavidescu.ro/",
 "dept_note": "Moldovan producer selling mainly in Romania — outside the Romanian LinkedIn capture; no employer profile located (checked 2026-08-21)",
 "ceo": ["Andrian Davidescu", "CEO",
   "Third-generation head of a family winery founded on his grandfather Ilie Davidescu's vineyard work on the left bank of the Prut; has built the Romanian business from 2.8 million lei in 2019 to 17.3 million lei in 2025 and argues publicly that Romanian and Moldovan producers should promote jointly.",
   "Bachelor: not found. Master: not found. PhD: not found.",
   "Family wine business; retail and HoReCa distribution; export; industry advocacy.",
   "https://www.zf.ro/zf-live/zf-live-andrian-davidescu-ceo-crama-domeniile-davidescu-din-22820233",
   "High confidence on the CEO title and commercial record from business-press interviews and reported results. Moldovan producer, listed here because Romania is its principal market."],
 "positions": [
   ["No dedicated vacancy page located", "Website review", "—", "No website listing found",
    f"Official website checked {CHECK}",
    "The site serves wines and story sections with no careers or vacancy route.",
    "https://domeniiledavidescu.ro/"],
   ["No Romanian job-board employer profile located", "Job-board review", "—",
    "No employer profile found", f"BestJobs checked {CHECK}",
    "Unlike the Romanian producers in this workbook, no BestJobs employer profile was located — consistent with production being based in Moldova.",
    "https://wineofmoldova.com/en/domeniile-davidescu-winery/"]],
 "campaigns": [
   ["2019 onward", "Romania-first market strategy", "Route to market",
    "Romania is the winery's principal market; revenue grew roughly six-fold from 2.8 million lei in 2019 to 17.3 million lei in 2025",
    "A Moldovan producer that treats Romania as home market rather than export has to win on shelf economics, not on curiosity.",
    "https://www.bursa.ro/domeniile-davidescu-a-inregistrat-o-crestere-de-peste-28-procente-a-vanzarilor-in-2025-47150957"],
   ["2025", "Retail expansion drove sales up more than 28%", "Retail / trade",
    "Growth in Romanian grocery listings is named as the engine behind a 17.3 million lei year",
    "The growth story is a distribution story, which is what a premium positioning claim has to be measured against.",
    "https://revistaprogresiv.ro/stiri/fmcg/extinderea-in-retail-a-adus-un-plus-de-peste-28-a-afacerilor-cramei-domeniile-davidescu-in-2025/"],
   ["2026", "Own online store, HoReCa push and a classic-method sparkling", "Product / channel launch",
    "Stated plans to sell direct, develop the on-trade and add a bottle-fermented sparkling wine, targeting over 20% growth",
    "Three moves that each reduce dependence on grocery shelf space after a year won on it.",
    "https://www.profit.ro/povesti-cu-profit/retail/domeniile-davidescu-cresc-si-pregatesc-noi-lansari-vinurile-vedeta-ale-semestrului-22191291"],
   ["Recurring", "„Promovare comună” advocacy", "Category leadership / PR",
    "The CEO publicly argues that Romanian and Moldovan producers are all small against regions with centuries of brand equity and should promote together",
    "Positioning the company as an industry voice earns coverage that product news alone would not.",
    "https://vinul.ro/ceo-andrian-davidescu-sustin-promovarea-comuna-suntem-cu-totii-mici-fata-de-regiunile-cu-sute-de-ani-de-brand-equity.html"],
   ["Recurring", "Three-generation family narrative", "Brand storytelling",
    "Grandfather Ilie Davidescu, artisan winemaker and beekeeper, is the origin story carried through to the current generation",
    "Continuity is the premium claim for a company whose Romanian trading history is only a few years long.",
    "https://www.comunicatedepresa.ro/dwf/povestea-vinurilor-domeniile-davidescu-crama-care-a-crescut-odata-cu-familia1"]],
 "people": [],
 "takeaway": ["No open role found and no Romanian job-board employer profile located, consistent with production being based in Moldova.",
   "A distribution-led growth story in Romanian retail, wrapped in a three-generation family narrative and reinforced by public industry advocacy",
   "Romania-first strategy; +28% retail-driven growth in 2025; online store, HoReCa and sparkling launches for 2026; promovare comună advocacy",
   "https://www.bursa.ro/domeniile-davidescu-a-inregistrat-o-crestere-de-peste-28-procente-a-vanzarilor-in-2025-47150957",
   "Moldova-based producer, included because Romania is its main market — not a Romanian winery. Commercial results are unusually well documented; no marketing or sales staff are named."],
},
{
 "name": "SERVE Ceptura",
 "members": None,
 "bestjobs": ("https://www.bestjobs.eu/company-profile/serve-ceptura", 8),
 "site": "https://www.serve.ro/",
 "dept_note": "No LinkedIn capture available; BestJobs employer profile lists 8 alumni (checked 2026-08-21). Part of Purcari Wineries since May 2026",
 "ceo": ["Mihaela Tyrel de Poix", "President and co-founder (until the Purcari acquisition)",
   "Co-founded SERVE — Societatea Euro Română de Vinuri de Excepție — in 1994 with her husband, the Corsican Count Guy Tyrel de Poix, and led the roughly 10 million lei business after his death; the winery works about 60–65 hectares at Ceptura and bottles some 500,000 wines a year on a turnover near 2 million euro.",
   "Bachelor: not found. Master: not found. PhD: not found.",
   "Wine entrepreneurship; estate leadership; native-variety advocacy; premium brand building.",
   "https://www.businessmagazin.ro/lideri/povestea-romancei-care-a-ajuns-contesa-iar-acum-conduce-un-business-de-10-milioane-de-lei-intr-un-domeniu-dominat-de-barbati-16387670",
   "High confidence on founding and leadership. Purcari Wineries completed its acquisition of SERVE Ceptura on 18 May 2026, so the leadership arrangement is likely to change; oenologist is Sabin Banița."],
 "positions": [
   ["No dedicated vacancy page located", "Website review", "—", "No website listing found",
    f"Official website checked {CHECK}",
    "The site serves wines, estate and shop sections with no careers or vacancy route.",
    "https://www.serve.ro/"],
   ["BestJobs employer profile (8 alumni)", "Job-board review", "Ceptura, Prahova",
    "Employer profile active; no open role visible at check", f"BestJobs company profile checked {CHECK}",
    "No live listing was visible at check. Recruitment may move to the Purcari group route following the May 2026 acquisition.",
    "https://www.bestjobs.eu/company-profile/serve-ceptura"]],
 "campaigns": [
   ["1994 onward", "Fetească Neagră restoration mission", "Category leadership",
    "The founders' stated purpose was to restore the dignity of Romania's flagship native red after decades of overproduction",
    "A mission bigger than the brand: the winery's marketing has always been about a grape variety, which is why its authority outlasts individual vintages.",
    "https://business-review.eu/lifestyle/food-wine/serve-winery-30-years-of-excellence-in-the-production-and-promotion-of-romanian-wine-269267"],
   ["2024", "Thirty-year anniversary programme", "Heritage / anniversary",
    "Communications marking three decades since 1994 as Romania's first private winery established after 1989",
    "Primacy is the one claim a competitor cannot buy, and an anniversary is the occasion to restate it.",
    "https://www.revistabiz.ro/crama-serve-30-de-ani-in-productia-si-promovarea-vinului-romanesc/"],
   ["Recurring", "250+ medals and the first 90-plus Parker Fetească Neagră", "Awards / reputation",
    "More than 250 medals since 1996 and the first Romanian Fetească Neagră rated above 90 Parker points",
    "A quantified critical record substitutes for advertising in a portfolio sold largely through specialists and on-trade.",
    "https://business-review.eu/lifestyle/food-wine/serve-winery-30-years-of-excellence-in-the-production-and-promotion-of-romanian-wine-269267"],
   ["2025", "„Povești cu vinuri românești” Best White Wine", "Awards / reputation",
    "First place in the Best White Wine category at the competition's tenth edition",
    "Keeps a current domestic result on the board alongside the historic international record.",
    "https://www.revistabiz.ro/crama-serve-30-de-ani-in-productia-si-promovarea-vinului-romanesc/"],
   ["Recurring", "Vinul Cavalerului, Terra Romana and the Cuvée ladder", "Portfolio marketing",
    "An accessible knight brand, a mid-tier Terra Romana and named super-premium Cuvées — Charlotte, Guy de Poix, Clemence, Amaury, Sissi and Pacs",
    "The Cuvées are named after family members, which ties the top of the range to the founding story rather than to a vineyard.",
    "https://www.crameromania.ro/crame/s.e.r.v.e.-crama-terra-romana-vinul-cavalerului-cuvee-charlotte-amaury-7.html"],
   ["May 2026", "Acquisition by Purcari Wineries completed", "Corporate / ownership",
    "Purcari announced completion after all corporate and regulatory approvals; about 60 hectares and 500,000 bottles join the group, 1.5 km from Crama Ceptura",
    "Two Ceptura names now sit under one owner: the heritage brand and the volume brand, which is a portfolio question the group has yet to answer publicly.",
    "https://www.zf.ro/burse-fonduri-mutuale/bursa-purcari-a-finalizat-achizitia-cramei-serve-ceptura-una-dintre-23154069"]],
 "people": [],
 "takeaway": ["No open role found. Recruitment presence is a BestJobs employer profile with 8 alumni; recruitment may move to the Purcari group route after the May 2026 acquisition.",
   "Primacy and mission: Romania's first post-1989 private winery, built on restoring Fetească Neagră and a quantified critical record, now inside the Purcari group",
   "Fetească Neagră restoration mission; 30-year anniversary (2024); 250+ medals and first 90-plus Parker FN; Povești cu vinuri românești 2025; Purcari acquisition (May 2026)",
   "https://business-review.eu/lifestyle/food-wine/serve-winery-30-years-of-excellence-in-the-production-and-promotion-of-romanian-wine-269267",
   "Part of Purcari Wineries since 18 May 2026 — kept as its own row because its brands, team and campaigns ran independently until then. No marketing or sales staff are named in public sources."],
},
]

# Top-ups for wineries already in the workbook (existing sheet names kept verbatim).
TOPUP_POSITIONS = [
 ["Davino Winery", "BestJobs employer profile (4 alumni)", "Job-board review", "Ceptura, Prahova / Bucharest",
  "Employer profile active; no open role visible at check", f"BestJobs company profile checked {CHECK}",
  "A second recruitment route beyond the LinkedIn listing already recorded: the winery keeps a BestJobs employer profile. No live listing was visible at check.",
  "https://www.bestjobs.eu/company-profile/davino"],
 ["Budureasca", "BestJobs employer profile", "Job-board review", "Gura Vadului, Prahova",
  "Employer profile active; no open role visible at check", f"BestJobs company profile checked {CHECK}",
  "The employer profile carries a company description and links to budureasca.ro; no live listing was visible at check.",
  "https://www.bestjobs.eu/company-profile/budureasca"],
 ["Domeniile Averesti", "BestJobs employer profile (2 alumni)", "Job-board review", "Averești, Vaslui",
  "Employer profile active; no open role visible at check", f"BestJobs company profile checked {CHECK}",
  "A recruitment route the official-website review did not surface. No live listing was visible at check.",
  "https://www.bestjobs.eu/company-profile/domeniile-averesti"],
]

TOPUP_CAMPAIGNS = [
 ["Davino Winery", "May 2026", "Vast 2025 and Iacob 2025 at RO-Wine Spring", "Product launch",
  "Two new white wines premiered at the RO-Wine Spring 2026 trade and consumer fair on 23 May 2026",
  "Continues the pattern already recorded for Davino: named premieres introduced at a curated fair rather than through retail promotion.",
  "https://winesofromania.com/en/new-wines-and-must-try-labels-at-ro-wine-spring-2026/"],
 ["Domeniile Averesti", "May 2026", "First traditional-method Zghihară and first barrel-aged Chardonnay", "Product launch",
  "A traditional-method sparkling Zghihară in the Diamond Selection range and the estate's first oak-aged Chardonnay, both shown at RO-Wine Spring 2026",
  "Extends the indigenous-variety premiumisation already recorded into the sparkling category, where Zghihară has no established competitor.",
  "https://winesofromania.com/en/new-wines-and-must-try-labels-at-ro-wine-spring-2026/"],
]
