# -*- coding: utf-8 -*-
"""Curated Campaign Evidence rows from the 2021-2026 sweep.

Every row is a dated item found on the winery's own news channel or in the
Romanian marketing press, with the source URL it came from.  Rows marked
"c. YEAR" are IQads articles whose date is inferred from that publisher's
article sequence, calibrated against four articles with known dates.
"""

SWEEP = [
# ---------------------------------------------------------------- Jidvei ----
["Jidvei","Feb. 2021","Mysterium extended into super-premium sparkling","Product launch",
 "Traditional-method sparkling added to the existing Mysterium range",
 "Stretches an established premium name into a new category instead of creating one, which is the cheaper way to enter sparkling.",
 "https://www.jidvei.ro/de-azi-mysterium-inseamna-si-vinuri-spumante-super-premium-obtinute-prin-metoda-traditionala/"],
["Jidvei","Mar. 2021","„Vin și Gust”","Gastronomy partnership",
 "A project pairing the wine range with Romanian gastronomy, launched in the middle of the pandemic restaurant closures",
 "Starts a food-and-wine platform precisely when the on-trade was shut — the audience was at home and cooking.",
 "https://www.jidvei.ro/vin-si-gust-un-nou-proiect-jidvei-in-care-gastronomia-si-arta-vinului-isi-dau-mana/"],
["Jidvei","Aug. 2021","„Must de la Jidvei”, seventh edition","Seasonal promotion",
 "Annual harvest-season must campaign, run every year since; further editions recorded in 2023 and 2024",
 "The only fixture in the calendar that repeats identically each autumn — a habit rather than a campaign.",
 "https://www.jidvei.ro/jidvei-da-startul-celei-de-a-saptea-editii-a-campaniei-must-de-la-jidvei/"],
["Jidvei","Sept. 2021","Art Safari Bucharest","Sponsorship / arts",
 "Ten days, five senses, two wines — Jidvei present at the Bucharest art fair",
 "The first of the art partnerships that later scale to Pompidou and Cannes; the pattern starts at home.",
 "https://www.jidvei.ro/10-zile-5-simturi-2-vinuri-cu-jidvei-la-art-safari-bucharest/"],
["Jidvei","Jan. 2023","Cocktails by Jidvei platform","Brand platform",
 "A cocktail platform described as unique in Romania, putting still wine into mixed drinks",
 "Attacks the occasion problem directly: if wine loses to spirits at parties, make wine the base of the party drink.",
 "https://www.jidvei.ro/platforma-cocktails-by-jidvei-o-initiativa-unica-in-romania/"],
["Jidvei","Jun. 2023","Iluziv by Jidvei","Product launch",
 "A new range launched as a first for the Romanian wine market",
 "A separate range name lets the house test a different style without touching the Jidvei masterbrand.",
 "https://www.jidvei.ro/noua-gama-de-vinuri-iluziv-by-jidvei-o-premiera-pe-piata-vinului-din-romania/"],
["Jidvei","Jul. 2023","WeinRun","Experiential / sport",
 "A running challenge through the vineyards, the forerunner of the Weinland Trails marathon",
 "Sport gets people onto the estate for a day; the event later grows into the branded Weinland Trails property.",
 "https://www.jidvei.ro/weinrun-o-provocare-lansata-de-jidvei-iubitorilor-de-sport-si-natura/"],
["Jidvei","Mar. 2023","D.O.C. Jidvei communication","Provenance claim",
 "Appellation status communicated as a step forward in the art of wine, followed by protected-designation (DOP) status in January 2025",
 "Regulatory recognition is turned into consumer messaging — a rare case of paperwork used as advertising.",
 "https://www.jidvei.ro/d-o-c-jidvei-este-un-pas-mai-departe-in-arta-vinului-si-nu-ne-oprim-aici/"],
["Jidvei","Mar. 2024","Brâncuși at Centre Pompidou","Cultural diplomacy",
 "Official wine of the vernissage of the largest Brâncuși exhibition in the world, in Paris, with 2,800 visitors at the opening",
 "Buys association with the one Romanian artist the world already knows, in the institution that certifies him.",
 "https://www.iqads.ro/articol/67645/jidvei-alaturi-de-2800-de-vizitatori-la-vernisajul-brancusi-de-la-paris"],
["Jidvei","Jul.–Aug. 2024","Romanian Olympic Team partnership","Sports / national pride",
 "COSR partnership around the Paris Olympics, alongside five years of the „Jidvei – Viitor prin Educație” association sponsoring the committee",
 "The sponsorship is old; the Paris Games are the moment it finally gets communicated.",
 "https://www.jidvei.ro/jocurile-olimpice-de-la-paris-ne-au-adus-mai-aproape-de-sportivii-romani-printr-un-parteneriat/"],
["Jidvei","Nov. 2024","„Eu sunt Jidvei” brand platform","Brand platform",
 "Born in the heart of Transylvania, perfected in the Land of Wine — a first-person masterbrand line",
 "After three years of borrowed cultural prestige, the brand finally states who it is in its own voice.",
 "https://www.jidvei.ro/eu-sunt-jidvei-nascut-in-inima-transilvaniei-desavarsit-in-tara-vinului/"],
["Jidvei","Dec. 2024","Verjus Jidvei","Product launch",
 "The first Romanian product of its kind, aimed at cooking enthusiasts",
 "A non-wine product from wine grapes: extends the gastronomy platform into the kitchen where „Vin și Gust” started.",
 "https://www.jidvei.ro/lansam-verjus-jidvei-primul-produs-romanesc-de-acest-tip-dedicat-celor-pasionati-de-gastronomie/"],
["Jidvei","2024–2025","Castelul Bethlen-Haller as a destination brand","Wine tourism",
 "TopHotel Awards named the castle best wine-tourism destination in 2024 and distinguished it again in 2025; it hosts concerts including Alexandru Tomescu's Stradivarius recital in June 2025",
 "The estate's castle is run as a separate hospitality brand, which gives the wine a place people can visit and photograph.",
 "https://www.jidvei.ro/castelul-bethlen-haller-distins-la-tophotel-awards-2025/"],
["Jidvei","Sept. 2025","Vinars XO international premiere in Paris","Product launch / prestige",
 "The XO brandy revealed internationally in Paris rather than domestically",
 "Category extension into spirits, launched abroad so the Romanian trade reads it as an international product.",
 "https://www.jidvei.ro/jidvei-a-lansat-vinars-xo-in-premiera-internationala-la-paris/"],
["Jidvei","Sept. 2025","Official wine at IMPACT Bucharest with Michelle Obama","Sponsorship / prestige",
 "Official wine of the largest business and tech event in South-Eastern Europe, headlined by Michelle Obama",
 "Moves the prestige play from arts to business audiences — a different room, the same logic.",
 "https://www.jidvei.ro/michelle-obama-la-impact-bucuresti-jidvei-vinul-oficial-al-celui-mai-important-eveniment-de-business-tech-din-europa-de-sud-est/"],
["Jidvei","Apr. 2026","Romania at the Paris Book Festival, Grand Palais","Cultural diplomacy",
 "Jidvei accompanied Romanian literature to the Grand Palais and brought Transylvania to the Paris book fair",
 "The fourth consecutive year of a Paris cultural placement; by now it is a fixture, not an opportunity.",
 "https://www.jidvei.ro/grand-palais-gazduieste-literatura-romana-jidvei-o-insoteste-la-festivalul-de-carte-de-la-paris/"],
["Jidvei","Jul. 2026","„Vin la povești” with Sebastian Stan at Cannes","Content series / celebrity",
 "A rare Romanian-language interview with Sebastian Stan filmed at Cannes for the brand's own content series, as Jidvei returned as official wine of Romania at the festival",
 "Owned content replaces sponsorship signage: the brand now makes the thing people watch rather than appearing beside it.",
 "https://www.iqads.ro/articol/75910/sebastian-stan-intr-un-interviu-rar-in-limba-romana-la-cannes-pentru-seria-jidvei"],
["Jidvei","2026","EFFIE Awards România 2026","Awards / reputation",
 "Jidvei among the brands recognised at the Romanian EFFIE effectiveness awards",
 "An effectiveness prize, unlike a wine medal, is evidence the marketing itself worked.",
 "https://www.iqads.ro/relevant/jidvei"],
# --------------------------------------------------------------- Purcari ----
["Purcari Wineries","c. 2022","„Noi, nu! Niciodată!” manifesto campaign","Brand manifesto",
 "A manifesto campaign signed by Propaganda encouraging Romanians, run for Purcari Wineries",
 "The group's one purely emotional, non-product campaign in the period — everything else is awards, results or events.",
 "https://www.iqads.ro/articol/62431/noi-nu-niciodata-o-campanie-manifest-semnata-de-propaganda-pentru-purcari"],
["Purcari Wineries","2023–2026","Nocturne Night Run","Experiential / sport",
 "An owned night-running event at Château Purcari held every year from 2023 through the 2026 edition",
 "The estate's only annual owned property; four consecutive editions make it the group's most durable consumer touchpoint.",
 "https://purcariwineries.com/nocturne-night-run-editia-2026/"],
["Purcari Wineries","Dec. 2023","Cuvée de Purcari Adamant Edition","Product launch",
 "A sparkling edition given its own spotlight launch",
 "Sparkling is launched as a named edition rather than a line extension, which lets it carry a higher price.",
 "https://purcariwineries.com/spumantul-cuvee-de-purcari-adamant-edition-si-a-facut-aparitia-in-lumina-reflectoarelor/"],
["Purcari Wineries","2024–2025","Romanian Design Week partnership","Sponsorship / arts",
 "Château Purcari partnered Romanian Design Week for a second consecutive year in 2025, alongside Jazz in the Park and the Diploma Show",
 "Design and music festivals reach an urban audience that wine competitions never touch.",
 "https://purcariwineries.com/chateau-purcari-partener-la-romanian-design-week-2025-pentru-al-doilea-an-consecutiv/"],
["Purcari Wineries","Oct. 2024","„2X by 200” strategy launch","Corporate strategy",
 "A publicly launched strategy to double the group's main operating indicators",
 "Publishing a growth target is investor marketing: the audience is the Bucharest exchange, not the shelf.",
 "https://purcariwineries.com/purcari-lanseaza-noua-strategie-2x-by-200/"],
["Purcari Wineries","Dec. 2024","Mircea Lucescu as brand ambassador","Celebrity endorsement",
 "Partnership with the veteran football coach as group ambassador",
 "A single national figure with cross-generational recognition, used where the group has no celebrity of its own.",
 "https://purcariwineries.com/purcari-wineries-anunta-parteneriatul-cu-legendarul-antrenor-mircea-lucescu/"],
["Purcari Wineries","2024","Rara Neagră 2.0 and the Sapiens range","Product / category leadership",
 "A project dedicated to the native Rara Neagră variety, alongside the Sapiens range launched as „produced by man, created by nature”",
 "Native-variety work is positioned as research rather than marketing, which is how a volume producer buys critical credibility.",
 "https://purcariwineries.com/purcari-demareaza-proiectul-rara-neagra-2-0/"],
["Purcari Wineries","Jul. 2024","Vintech Innovations","Corporate / innovation",
 "A dedicated venture launched to lead the group's digital transformation",
 "Technology is communicated as a brand asset — unusual for a wine group and aimed squarely at investors.",
 "https://purcariwineries.com/purcari-wineries-lanseaza-vintech-innovations/"],
["Purcari Wineries","Mar. 2025","Château Purcari Orange wine","Product launch",
 "The estate stepped outside its own conventions to launch an orange wine",
 "A style aimed at a younger, specialist audience, launched under the flagship estate name rather than a side brand.",
 "https://purcariwineries.com/chateau-purcari-iese-din-tipare-si-lanseaza-vinul-orange/"],
["Purcari Wineries","Oct.–Nov. 2025","„BURSA” scholarships and student masterclasses","CSR / education",
 "A scholarship project for young specialists plus a masterclass programme for oenology students",
 "Recruitment marketing dressed as CSR, in an industry that competes hard for trained winemakers.",
 "https://purcariwineries.com/grupul-de-vinarii-purcari-lanseaza-un-proiect-unic-de-sustinere-a-tinerilor-specialisti-bursa/"],
["Purcari Wineries","Mar. 2026","First biodiversity monitoring results","ESG / research",
 "First results published from biodiversity monitoring in the Château Purcari vineyards",
 "Publishing measurements rather than intentions is what separates this from ordinary sustainability messaging.",
 "https://purcariwineries.com/primele-rezultate-ale-monitorizarii-biodiversitatii-in-podgoriile-chateau-purcari/"],
["Purcari Wineries","2024–2026","Continuous international medal communication","Awards / reputation",
 "Decanter, Concours Mondial de Bruxelles, Mundus Vini, Berliner Wine Trophy, Vinalies, Challenge International du Vin, London Wine Competition and VINARIUM results published as separate announcements through 2026",
 "Medals are treated as a publishing schedule rather than as occasional news — roughly one award story a month.",
 "https://purcariwineries.com/en/media/"],
# ------------------------------------------------------------- Gîrboiu -----
["Crama Gîrboiu","May 2021","Mundus Vini 2021 top distinctions","Awards / reputation",
 "The highest distinctions at Mundus Vini, the start of the run that becomes four consecutive Best Romanian Producer titles",
 "One competition is chosen and worked every year; the compounding title is worth more than scattered medals.",
 "https://cramagirboiu.ro/blog/cele-mai-inalte-distinctii-pentru-crama-girboiu-la-mundus-vini-2021/"],
["Crama Gîrboiu","Oct. 2021","„Pachet Vinuri Medaliate” gift packs","Retail promotion",
 "Medal-winning wines bundled as a gift pack for the season, alongside Berliner Wein Trophy communication",
 "Converts the awards story straight into a sellable product rather than leaving it as reputation.",
 "https://cramagirboiu.ro/blog/pachet-vinuri-medaliate-cadoul-perfect/"],
["Crama Gîrboiu","Feb. 2024","Best Producer at Mundus Vini, two years running","Awards / reputation",
 "A second consecutive Best Romanian Producer title in Germany, later extended to four",
 "The producer title licenses a quality claim across the whole range, which no single-wine medal can do.",
 "https://cramagirboiu.ro/blog/crama-girboiu-best-producer-2-ani-la-rand-la-mundus-vini-germania/"],
["Crama Gîrboiu","Jun. 2025","Decanter 2025 gold and Best Value","Awards / reputation",
 "Tectonic Fetească Neagră Barrique took gold and the Best Value title in London",
 "Best Value argues price-to-quality, which is the claim a mid-priced native red actually needs.",
 "https://cramagirboiu.ro/blog/crama-girboiu-aur-decanter-2025/"],
["Crama Gîrboiu","Jun. 2025","Bacanta Grand Gold at Concours Mondial de Bruxelles","Awards / reputation",
 "A Grand Gold described as a medal worth two decades of work",
 "A second flagship line given its own award story, so the reputation does not rest on Tectonic alone.",
 "https://cramagirboiu.ro/blog/bacanta-grand-gold-concours-mondial-bruxelles-2025/"],
["Crama Gîrboiu","2021–2026","Owned content programme, 207 posts","Content marketing",
 "A continuously published blog — food pairings, variety guides, serving advice, seasonal recipes and gift guides — running at roughly forty posts a year through 2026",
 "By far the largest owned-content operation of any winery here: the winery is buying search traffic rather than media.",
 "https://cramagirboiu.ro/blog/"],
["Crama Gîrboiu","Feb.–May 2025","„Roata Vinului”","Promotion / contest",
 "A prize-wheel mechanic run under a published regulation from 1 February to 31 May 2025",
 "A four-month window rather than a burst — built to run alongside the trade year instead of spiking it.",
 "https://cramagirboiu.ro/roata-vinului-2/regulament/"],
["Crama Gîrboiu","Dec. 2025","Christmas and New Year wine guide","Seasonal content",
 "A gift and selection guide published for the 2025 festive season",
 "The content programme is pointed at the one moment when wine is bought as a present.",
 "https://cramagirboiu.ro/blog/ghidul-vinurilor-pentru-craciun-si-revelion-2025/"],
# -------------------------------------------------------- Domeniile Ostrov --
["Domeniile Ostrov","Aug. 2022","Rosé volume leadership claim","Category leadership",
 "1.2 million litres of rosé sold in 2021 and a public claim to lead the quality rosé market, argued by CEO Oana Belu",
 "Leads with a volume number rather than a medal — the argument of a producer that sells through grocery retail.",
 "https://www.domeniileostrov.ro/blogs/blog/domeniile-ostrov-lider-pe-piata-vinului-rose-de-calitate"],
["Domeniile Ostrov","Dec. 2022","Year-end party with Smiley, Juno and Delia","Experiential / events",
 "A large end-of-year event headlined by three mainstream Romanian acts",
 "Mass-market music for a mass-market wine — the entertainment matches where the product sells.",
 "https://www.domeniileostrov.ro/blogs/blog/domeniile-ostrov-petrecere-cu-fast-la-final-de-2022"],
["Domeniile Ostrov","Jul. 2023","Distribution across Lidl, Kaufland, METRO, Cora and Auchan","Retail / trade",
 "Public communication of Dobrogea wines listed across the national grocery chains, alongside a 45 million lei turnover",
 "Distribution breadth is itself the message, aimed at trade and investors as much as at drinkers.",
 "https://www.domeniileostrov.ro/blogs/comunicate-de-presa/domeniile-ostrov-vinde-vinurile-din-dobrogea-in-lidl-kaufland-metro-cora-sau-auchan"],
["Domeniile Ostrov","Oct. 2024","Pelin relaunch","Product / heritage",
 "The bitter-sweet Pelin tradition brought back to Romanian attention as a branded product",
 "Reviving a folk drink gives a modern winery a heritage story it did not have to invent.",
 "https://www.domeniileostrov.ro/blogs/blog/domeniile-ostrov-readuce-in-atentia-romanilor-vinul-pelin"],
["Domeniile Ostrov","Apr. 2025","Online wine growth communication","E-commerce",
 "Romanians buying more wine online in 2025, with the winery reporting significant growth of its own",
 "Uses a category trend as the peg for its own e-commerce numbers — cheap credibility for a channel story.",
 "https://www.domeniileostrov.ro/blogs/blog/romanii-cumpara-mai-mult-vin-online-in-2025"],
# ------------------------------------------------------ Domeniile Davidescu -
["Domeniile Davidescu","2021","Chef partnership recipe series","Content / celebrity",
 "Recipe films with Sorin Bontea and Cătălin Scărlătescu pairing dishes with the winery's Rară Neagră, Fetească Neagră and rosé",
 "Television chefs supply both reach and the pairing occasion, which is what an unknown Moldovan label needs in Romania.",
 "https://domeniiledavidescu.ro/articole/"],
["Domeniile Davidescu","Sept. 2024","„La făcut de vin” with Mircea Bravo","Influencer content",
 "A film made with the comedian Mircea Bravo about winemaking in the Republic of Moldova",
 "Swaps the chef format for a comedian with a young national audience — same borrowed-reach logic, different demographic.",
 "https://domeniiledavidescu.ro/articole/"],
["Domeniile Davidescu","Feb. 2026","Official Supplier to the Royal House of Romania","Prestige endorsement",
 "The winery became an official supplier to the Romanian Royal House",
 "A warrant is the strongest available prestige signal in Romania, and it settles the origin question a Moldovan producer otherwise carries.",
 "https://domeniiledavidescu.ro/articole/domeniile-davidescu-devine-furnizor-al-casei-regale-a-romaniei/"],
["Domeniile Davidescu","Jan.–Feb. 2026","Owned content sprint, 29 posts in six weeks","Content marketing",
 "A concentrated run of pairing guides, variety explainers and gift recommendations published across January and early February 2026",
 "A burst rather than a drip: content timed to the festive and gifting window, then stopped.",
 "https://domeniiledavidescu.ro/articole/"],
# ----------------------------------------------------------- Carastelec -----
["Carastelec Winery","Oct.–Dec. 2021","Record medal haul and Chairman's Trophy","Awards / reputation",
 "A record number of medals in London, then Carassia Rosé Brut taking both the Chairman's Trophy and National Champion of Romania",
 "The competition result is published in Romanian, English and Hungarian — the audience is export buyers as much as locals.",
 "https://carastelecwinery.com/carassia-rose-brut-este-anul-acesta-campion-national-si-titular-al-chairmans-trophy/"],
["Carastelec Winery","Nov. 2022","Third consecutive National Champion title","Awards / reputation",
 "A third National Champion title for the Carassia sparkling range",
 "Consecutive titles turn a competition record into a category claim: the best sparkling in the country, every year.",
 "https://carastelecwinery.com/un-nou-titlu-de-campion-national-pentru-spumantele-carassia/"],
["Carastelec Winery","Sept.–Nov. 2023","Blanc de Blancs World Champion and triple magnum gold","Awards / reputation",
 "Collection #1 named the year's best Blanc de Blancs, alongside three golds for the Carassia magnums",
 "A world title in a defined style is the strongest result a specialist producer can get, and it names the wine rather than the winery.",
 "https://carastelecwinery.com/carassia-wins-the-blanc-de-blancs-world-champion-title/"],
["Carastelec Winery","Sept. 2024","„100% GOLD” — four of four","Awards / reputation",
 "Four gold medals from four entries at the Champagne & Sparkling Wine World Championships",
 "A perfect strike rate is a better headline than a bigger medal count, and the campaign is built on that framing.",
 "https://carastelecwinery.com/100-gold-4-out-of-4-gold-medals-at-champagne-sparkling-wine-world-championships-2024/"],
["Carastelec Winery","Nov. 2025","„Consistently among the finest”","Awards / reputation",
 "The 2025 communication shifts from individual results to the consistency of the record across editions",
 "After five years of medals the story stops being any one win and becomes the streak itself.",
 "https://carastelecwinery.com/carassia-consistently-among-the-finest-at-cswwc/"],
# ------------------------------------------------------------- Murfatlar ----
["Murfatlar","Nov. 2023","„Jumătate vin, jumătate viață” platform","Brand platform",
 "A communication platform launched by Murfatlar Vinul, created by the Propaganda agency",
 "The first coherent brand platform after the ownership change — the point where the rebuild becomes visible.",
 "https://www.iqads.ro/relevant/murfatlar"],
["Murfatlar","2024","Lacrima lui Ovidiu 12 and „Moștenire pentru viitor”","Product / heritage",
 "A twelve-year expression of the historic Lacrima lui Ovidiu, alongside a heritage-framed communication",
 "The oldest asset in the portfolio is used to argue continuity through a change of owner.",
 "https://murfatlar-vinul.ro/noutati/"],
["Murfatlar","Feb. 2025","Vermut and Aperitiv Mamaia","Product launch",
 "Two aperitif products launched under the Mamaia name",
 "Moves outside wine into aperitifs, using a seaside place name the whole country recognises.",
 "https://murfatlar-vinul.ro/noutati/"],
["Murfatlar","Jul. 2026","Aerosoli Prosecco","Product launch",
 "A Prosecco added to the Aerosoli line, which also collected gold at Vinalies Internationales 2026",
 "An Italian-style sparkling under a Romanian sub-brand, launched into the category growing fastest at retail.",
 "https://murfatlar-vinul.ro/noutati/"],
# ---------------------------------------------------------------- Zarea -----
["Zarea","Jun. 2022","ZAREA Free 0,0%","Product launch",
 "An alcohol-free sparkling launched as „freedom without alcohol”",
 "First mover among these wineries into no-alcohol, a category driven by exactly the young urban drinkers sparkling needs.",
 "https://zarea.ro/zarea-free-00-libertate-fara-alcool/"],
["Zarea","2022","Sparkling-wine education series","Content marketing",
 "A run of explainer posts on bubbles, corks, wellbeing and reasons to drink sparkling in summer",
 "Category education rather than brand advertising — the job is to make sparkling an everyday purchase, not a New Year one.",
 "https://zarea.ro/stiri/"],
["Zarea","Feb. 2023","Entry into quality wines with Domeniile Dealu Mare","Portfolio / partnership",
 "Zarea moved into quality still wines alongside the Domeniile Dealu Mare group of companies",
 "A sparkling house borrowing a still-wine estate rather than building one, which is the fast way into a new shelf.",
 "https://zarea.ro/zarea-intra-pe-piata-vinurilor-de-calitate-alaturi-de-grupul-de-firme-domeniile-dealu-mare/"],
["Zarea","Nov. 2025","Ilie Dumitrescu campaign","Celebrity endorsement",
 "A campaign about precision, style and team spirit built around the footballer Ilie Dumitrescu",
 "A 1990s national-team figure speaks to the generation that already buys Zarea, rather than chasing a new one.",
 "https://zarea.ro/zarea-isi-intareste-echipa-cu-ilie-dumitrescu-o-campanie-despre-precizie-stil-si-spirit-de-echipa/"],
# ------------------------------------------------------------ others --------
["Beciul Domnesc","c. 2026","„Somelier de Grătar” promotional campaign","Promotion / contest",
 "A promotional campaign launched with an agency partner, pairing the range with barbecue occasions",
 "Barbecue is the summer occasion where wine loses to beer; the campaign attacks it directly.",
 "https://www.iqads.ro/relevant/beciul-domnesc"],
["Cramele Cotnari","Apr. 2024","„Crama Transparentă”","Brand platform / transparency",
 "A campaign and dedicated platform at cramatransparenta.ro offering live streaming from the winery, access to all three cellars and a phone line to company representatives — presented as a Romanian first",
 "Radical transparency is a defensible claim for the largest producer of native varieties, and it answers the industrial-scale objection head on.",
 "https://www.bursa.ro/cotnari-lanseaza-campania-crama-transparenta-82564254"],
["Cramele Recas","Feb. 2023","Principal partner of Timișoara 2023","Sponsorship / culture",
 "Principal partner of Timișoara, European Capital of Culture in 2023, in the winery's home county",
 "The one year the region is the centre of European cultural attention, and the local producer owns it.",
 "https://www.iqads.ro/articol/63200/cramele-recas-partener-principal-al-timisoarei-capitala-europeana-a-culturii"],
["Cramele Recas","Recurring","„Brunch in the sky” launch of Conacul Ambrozy","Product launch / experiential",
 "The Dinner in the Sky format adapted to launch a wine, with a platform for 22 guests raised to about 40 metres",
 "A launch stunt built for photographs — the wine is introduced as an experience journalists will publish.",
 "https://foodcrew.ro/advertoriale/lansare-de-vin-la-inaltime-conacul-ambrozy-cramele-recas/"],
["Tohani Romania","c. 2021","Experiential enotourism — public harvest","Wine tourism",
 "The company invited the public to pick grapes at the Tohani estate, giving a bottle for every five buckets picked",
 "Turns unpaid labour into a paid-for experience, and the harvest into a marketing event.",
 "https://www.iqads.ro/articol/56112/tohani-romania-mutare-in-enoturism-experiential-compania-cheama-publicul-la"],
["Tohani Romania","2023–2025","Subcarpați concerts in the vineyard","Experiential / events",
 "The band Subcarpați played in the vineyard for a third consecutive year in 2025, joined by Frate Gheorghe, as part of the harvest celebration",
 "One act booked three years running builds an annual fixture; the music is Romanian folk-hip-hop, which matches the native-variety story.",
 "https://www.iabilet.ro/bilete-tohani-concert-subcarpati-muzica-si-cules-de-vie-113453/"],
["Liliac Winery","c. 2021","young.LILIAC contemporary-artist labels","Art collaboration",
 "A wine reworked every year under the inspiration of contemporary artists, described as the only Romanian wine that transforms annually",
 "An annual reason to relaunch the same wine, and a collectible logic that suits a boutique estate.",
 "https://www.iqads.ro/relevant/liliac"],
["Budureasca","c. 2018–2021","Perceptum and The Mansion campaigns","Agency-led brand building",
 "Perceptum signed the promotion of the Centenar collection and integrated video into the marketing mix; The Mansion Advertising produced „Budureasca Premium, o poveste despre perfecțiune”",
 "Sustained agency relationships rather than one-off briefs — unusual at this size and visible in the consistency of the range's look.",
 "https://www.iqads.ro/relevant/budureasca"],
["Budureasca","Apr. 2026","Food-waste prevention communication","CSR / sustainability",
 "A published position on preventing and reducing food waste, alongside the sustainable development strategy declaration",
 "Sustainability is communicated as compliance and policy rather than as a consumer campaign.",
 "https://budureascawines.com/blog/"],
["SERVE Ceptura","Feb.–Mar. 2026","Fetească Neagră content and „Making of SERVE wine”","Content marketing",
 "A run of owned content on Fetească Neagră, the estate's story, a viticultural dictionary and a making-of series, published in the weeks before the Purcari deal was announced",
 "The house restates what it stands for immediately before ownership changes — the founding mission put on the record.",
 "https://www.serve.ro/"],
]
